---
  - name: install_protobuf | download protobuf
    get_url: url={{protobuf_url}} dest=/tmp/protobuf.tar.gz     
    tags: protobuf

  - name: install_protobuf | rm protobuf tar
    shell: rm -rf /usr/local/bin/protoc
    tags: protobuf

  - name: install_protobuf | untar Protobuf
    unarchive: copy=no src=/tmp/protobuf.tar.gz dest=/tmp/
    tags: protobuf

  - name: install_protobuf | configure, make, make install
    shell: cd /tmp/protobuf-2.5.0 ; ./configure --prefix=/opt ; make clean ; make install
    tags: protobuf

  - name: install_protobuf | chown -R jenkins:users /opt
    shell: chown -R jenkins:users /opt
    tags: protobuf
