---
  - name: install_libraries | zypper in
    sudo: yes
    zypper: pkg={{item}} disable_gpg_check=yes state=latest 
    with_items:
      - http://ftp.twaren.net/Linux/OpenSuSE/repositories/M17N/SLE_11_SP3/x86_64/googletest-1.7.0-16.1.x86_64.rpm
      - http://ftp.twaren.net/Linux/OpenSuSE/repositories/M17N/SLE_11_SP3/x86_64/googletest-devel-1.7.0-16.1.x86_64.rpm
    tags: install_libraries

  - name: "Installing Libraries"
    sudo: yes
    sudo_user: root
    zypper: pkg={{item}} disable_gpg_check=yes state=latest
    tags: install_libraries
    with_items:
      - gcc-c++ 
      - wget
      - curl
      - subversion
      - snappy-devel
      - lzo-devel
      - asciidoc
      - libcppunit-devel
      - gcc
      - automake 
      - autoconf
      - libconfuse-devel
      - fuse-devel
      - docbook-utils 
      - docbook5-xsl-stylesheets
      - xmlformat
      - xmlto 
      - libxslt
      - libopenssl-devel
      - docbook_5
      - libssh-devel
      - openldap2-devel
      - libmysqlclient-devel
      - texlive-latex-doc
      - cmake
      - ant
      - ant-nodeps 
      - ant-trax
      - python-devel
      - python-setuptools
      - libxml2-devel
      - libxslt-devel
      - krb5-devel
      - sqlite3-devel
      - gd-devel
      - libpng-devel
      - libjpeg-devel
      - cairo-devel
      - freetype2-devel
      - glib2-devel
      - intltool
      - libart_lgpl-devel
      - pango-devel
      - gettext-tools
      - ruby-devel
      - lua-devel
      - tcpd-devel
      - dejagnu
      - googletest-devel
      - rsh 
      - apache2-devel
      - pcre-devel  
      - libapr-util1-devel 
      - xorg-x11-devel 
      - fdupes 
      - tcl-devel 
      - libconfuse-devel 
      - rrdtool-devel 
      - libtool

  - name: install_libraries | s3cmd , fakeroot
    sudo: yes
    sudo_user: root
    tags: install_libraries
    zypper: name="{{item}}" state=present
    with_items:
      - http://s3tools.org/repo/SLE_11/x86_64/s3cmd-1.0.0-4.1.x86_64.rpm
      - "{{fakeroot_rpm_url}}"


