---
 - name: enable mysql
   service:
     name: "{{ __mysql_daemon }}"
     runlevel: 235
     enabled: yes

 - name: start mysql
   service:
     name: "{{ __mysql_daemon }}"
     state: started

 - name: stop mysql
   service:
     name: "{{ __mysql_daemon }}"
     state: stopped

 - name: restart mysql
   service:
     name: "{{ __mysql_daemon }}"
     state: restarted
