---
  - name: install_libraries | uninstall
    become: yes
    become_user: root
    yum: pkg={{item}} state=absent
    with_items:
      - postgresql-libs
      - rrdtool-1.2.27
      - ruby-libs-1.8.7.352
      - epel-release
    ignore_errors: yes

  - name: install_libraries | centos
    become: yes
    become_user: root
    yum: pkg={{item}} state=latest
    with_items:
#      - cmake3
      - gd-devel
      - libpng-devel
#      - libjpeg-devel
      - cairo-devel
      - gettext-devel
      - sqlite-devel
      - intltool
      - lua-devel
      - pango-devel
#      - xulrunner-devel
      - openssl-devel
      - intltool
      - cairo-devel
      - libxml2-devel
      - ruby
      - ruby-devel
      - tcl-devel
      - gettext-devel
      - tk-devel
      - python-setuptools
      - rrdtool-python
#      - clamav
      - python-virtualenv
      - openssh-clients
      - lsb
      - wget
      - openldap-devel
      - mysql-devel
      - fuse-devel
      - lzo-devel
      - pam-devel
      - tetex-latex
#      - fakeroot
      - gcc
      - cppunit
      - cppunit-devel
      - snappy-devel
      - xalan-j2
      - glib2
      - cpio
      - cppunit-devel
      - ant
      - libstdc++
      - ant-apache-bcel
      - zlib-devel
      - gcc-c++
      - rpm-build
      - redhat-rpm-config
      - libtool
      - fuse
      - fuse-devel
      - fuse-libs
      - xmlto
      - expect
      - cmake
      - libffi-devel
#      - s3cmd
      - curl-devel
      - createrepo
      - subversion
      - gcc-gfortran
      - rsync
      - autoconf
      - automake
#      - centos-release-scl
      - libevent-devel
      - bison
      - doxygen
#      - leveldb-devel
      - libuuid-devel
      - libcurl-devel
#      - devtoolset-6
#      - pdsh
#      - ant-nodeps
      - graphviz
#      - p7zip
#      - p7zip-plugins
      - boost-devel
      - boost-filesystem
      - boost-system
      - libxslt-devel
      - rpm-sign
      - asciidoc
      - bzip2-devel
      - ncurses-devel
      - readline-devel
      - postgresql-devel
