---
  - include_vars: ../../common/vars/{{project}}_secrets.yml

  - name: centos_env_setup | download 
    get_url: url="{{ rpm_gpg_url }}" dest=/tmp

  - name: centos_env_setup | rpm --import
    sudo: yes
    sudo_user: root
    shell: rpm --import /tmp/RPM-GPG-KEY-Jenkins

  - name: centos_env_setup | setup rpmmacros
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url="{{ rpmmacros_url }}" dest={{builds_home}}/

  - name: centos_env_setup | unarchive rpmmacros.tar.gz
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{builds_home}}/{{ rpmmacros_url | basename }} dest={{builds_home}}/
