---
  - include_vars: ../../common/vars/{{project}}_secrets.yml

  - name: centos_env_setup | download 
    get_url: url="{{ rpm_gpg_url }}" dest=/tmp

  - name: centos_env_setup | rpm --import
    sudo: yes
    sudo_user: root
    shell: rpm --import /tmp/RPM-GPG-KEY-Jenkins

  - name: centos_env_setup | setup rpmmacros
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url="{{ rpmmacros_url }}" dest={{build_user_home}}/

  - name: centos_env_setup | unarchive rpmmacros.tar.gz
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ rpmmacros_url | basename }} dest={{build_user_home}}/

  - name: centos_env_setup | create jenkins_rpmmacros directory
    sudo: yes
    sudo_user: "{{ build_user }}"
    file: path={{item}} state=directory owner="{{ build_user }}"
    with_items:
      - "{{build_user_home}}/profiles/jenkins/jenkins_rpmmacros"

  - name: centos_env_setup | unarchive rpmmacros.tar.gz
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ rpmmacros_url | basename }} dest={{build_user_home}}/profiles/jenkins/jenkins_rpmmacros/
