---
  - name: install_libraries | uninstall 
    sudo: yes
    sudo_user: root
    yum: pkg={{item}} state=absent
    with_items:
      - postgresql-libs
      - rrdtool-1.2.27
      - ruby-libs-1.8.7.352
      - epel-release
    ignore_errors: yes

  - name: centos7_repo_setup | install epel release
    sudo: yes
    sudo_user: root
    when: ansible_distribution_major_version|int == 7
    yum: name='http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/epel-release-7-9.noarch.rpm' state=present

  - name: get epel-repo rpm RHEL6
    sudo: yes
    sudo_user: root
    shell: yum-config-manager --add-repo https://dl.fedoraproject.org/pub/epel/6/x86_64/
    when: ansible_distribution_major_version|int == 6

  - name: install_libraries | centos5 manual rpm install | epel && asciidoc
    sudo: yes
    sudo_user: root
    when: ansible_distribution_major_version|int == 5
    shell: rpm -Uvh {{item}}
    with_items:
      - http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/centos5/epel-release-5-4.noarch.rpm

  - name: install_libraries | download s3tools repo file
    sudo: yes
    sudo_user: root
    when: ansible_distribution_major_version|int == 5
    get_url: url=http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/centos5/s3tools.repo dest=/etc/yum.repos.d/s3tools.repo timeout=120

  - name: install_libraries | centos
    sudo: yes
    sudo_user: root
    yum: pkg={{item}} state=latest 
    with_items:
      - gd-devel
      - libpng-devel
      - libjpeg-devel
      - cairo-devel
      - gettext-devel
      - sqlite-devel
      - intltool
      - lua-devel
      - pango-devel
      - xulrunner-devel
      - openssl-devel 
      - intltool 
      - cairo-devel 
      - libxml2-devel 
      - ruby 
      - ruby-devel 
      - tcl-devel
      - gettext-devel 
      - tk-devel 
      - xulrunner-devel 
      - python-setuptools
      - rrdtool-python
      - clamav
      - python-virtualenv
      - openssh-clients
      - lsb 
      - wget 
      - openldap-devel
      - mysql-devel 
      - fuse-devel 
      - lzo-devel
      - pam-devel 
      - tetex-latex
      - fakeroot
      - gcc
      - cppunit 
      - cppunit-devel 
      - snappy-devel
      - xalan-j2
      - glib2
      - cpio
      - cppunit-devel
      - ant
      - libstdc++
      - ant-apache-bcel
      - zlib-devel
      - gcc-c++
      - rpm-build
      - redhat-rpm-config
      - libtool
      - fuse
      - fuse-devel
      - fuse-libs
      - xmlto
      - expect
      - cmake
      - libffi-devel
      - s3cmd
      - curl-devel
      - createrepo
      - subversion
      - gcc-gfortran
      - rsync
      - autoconf
      - automake
      - centos-release-scl
      - libevent-devel

  - name: install_libraries | install devtoolset-6
    sudo: yes
    sudo_user: root
    yum: name="devtoolset-6" state=present

  - name: install_libraries | install the 'Development tools' package group
    sudo: yes
    sudo_user: root
    yum: name="@Development tools" state=present
    when: ansible_distribution_major_version|int == 6

  - name: install_libraries | install alien
    sudo: yes
    sudo_user: root
    yum: name=http://dev.hortonworks.com.s3.amazonaws.com/REJENKINS/alien-8.81-2.noarch.rpm state=present
    when: ansible_distribution_major_version|int == 6

  - name: install_libraries | install asciidoc - centos5
    sudo: yes
    sudo_user: root
    shell: rpm -Uvh http://dev.hortonworks.com.s3.amazonaws.com/ARTIFACTS/centos5/asciidoc-8.6.9-1.el5.rf.noarch.rpm
    when: ansible_distribution_major_version|int == 5

  - name: install_libraries | non centos7 | pdsh, ant-nodeps
    sudo: yes
    sudo_user: root
    when: ansible_distribution_major_version|int != 7
    yum: pkg={{item}} state=latest
    with_items:
      - pdsh
      - ant-nodeps
      - graphviz

  - name: install_libraries | install 7zip
    sudo: yes
    sudo_user: root
    yum: pkg={{item}} state=latest
    with_items:
      - p7zip
      - p7zip-plugins

  - name: install_libraries | centos7 | install R
    sudo: yes
    sudo_user: root
    when: ansible_distribution_major_version|int == 7
    yum: name=R state=latest update_cache=yes
    tags: install_r

  - name: install_libraries | centos7 | leveldb-devel, boost-devel
    sudo: yes
    sudo_user: root
    when: ansible_distribution_major_version|int == 7
    yum: pkg={{item}} state=latest
    with_items:
      - leveldb-devel
      - boost-devel
      - cmake3
      - libuuid-devel
      - doxygen
      - libcurl-devel
