---
- name: centos_env_setup | download 
  get_url: url='http://s3.amazonaws.com/dev.hortonworks.com/RLENG/RPM-GPG-KEY-Jenkins' dest=/tmp

- name: centos_env_setup | rpm --import
  sudo: yes
  sudo_user: root
  shell: rpm --import /tmp/RPM-GPG-KEY-Jenkins

- name: centos_env_setup | setup rpmmacros
  sudo: yes
  sudo_user: "{{ build_user }}"
  get_url: url='http://s3.amazonaws.com/dev.hortonworks.com/RLENG/rpmmacros.tar.gz' dest={{builds_home}}/

- name: centos_env_setup | unarchive rpmmacros.tar.gz
  sudo: yes
  sudo_user: "{{ build_user }}"
  unarchive: copy=no src={{builds_home}}/rpmmacros.tar.gz dest={{builds_home}}/
