---
  - name: configure_clamav | run freshclam
    sudo: yes
    sudo_user: root
    shell: freshclam
    when: (ansible_distribution == 'Suse' and ansible_distribution == 'SLES')

  - name: configure_clamav | start clamav deamon
    service: name=clamd state=started
    when: (ansible_distribution != 'Suse' and ansible_distribution != 'SLES')

  - name: configure_clamav | copy whitelist file
    sudo: yes
    sudo_user: root
    copy: src="whitelist-signatures.ign2" dest="/var/lib/clamav/whitelist-signatures.ign2" force=yes
