---
  - include_vars: ../../common/vars/{{project}}_secrets.yml

  - name: Decvi | setup_user_configs | Download devci gpgkeys
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ devci_gpgkeys_url }}
            dest={{ build_user_home }}/{{ devci_gpgkeys_url | basename }}

  - name: Decvi | setup_user_configs | Unarchive devci gpgkeys
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ devci_gpgkeys_url | basename }}
        dest={{build_user_home}}/

  - name: Decvi | setup_user_configs | Download devci config-all
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ devci_config_all_url }}
            dest={{ build_user_home }}/{{ devci_config_all_url | basename }}

  - name: Decvi | setup_user_configs | Unarchive devci config-all
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ devci_config_all_url | basename }}
        dest={{build_user_home}}/

  - name: Decvi | setup_user_configs | Download devci rpmmacros
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ devci_rpmmacros_url }}
            dest={{ build_user_home }}/{{ devci_rpmmacros_url | basename }}

  - name: Decvi | setup_user_configs | Unarchive devci rpmmacros
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ devci_rpmmacros_url | basename }}
        est={{build_user_home}}/

  - name: Decvi | setup_user_configs | Download jenkins gpgkeys
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ jenkins_gpgkeys_url }}
            dest={{ build_user_home }}/{{ jenkins_gpgkeys_url | basename }}

  - name: Decvi | setup_user_configs | Uuarchive jenkins gpgkeys
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ jenkins_gpgkeys_url | basename }}
        dest={{build_user_home}}/

  - name: Decvi | setup_user_configs | Download jenkins config-all
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ jenkins_config_all_url }}
            dest={{ build_user_home }}/{{ jenkins_config_all_url | basename }}

  - name: Decvi | setup_user_configs | Unarchive jenkins config-all
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ jenkins_config_all_url | basename }}
        dest={{build_user_home}}/

  - name: Decvi | setup_user_configs | Download jenkins rpmmacros
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ jenkins_rpmmacros_url }}
            dest={{ build_user_home }}/{{ jenkins_rpmmacros_url | basename }}

  - name: Decvi | setup_user_configs | Unarchive jenkins rpmmacros
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ jenkins_rpmmacros_url | basename }}
        est={{build_user_home}}/
