---
- name: install_asciidoc | check if asciidoc is installed
  command: asciidoc --version
  register: check_asciidoc
  ignore_errors: yes

# check if "check_asciidoc" is defined and value is equal to desired asciidoc version
- name: install_asciidoc | "set fact if asciidoc version is {{ asciidoc_version }}"
  set_fact: asciidoc_exists="true"
  when: check_asciidoc.rc == 0 and check_asciidoc.stdout.find("{{asciidoc_version}}") != -1

- name: install_asciidoc | skip asciidoc installation
  debug: msg="skipping asciidoc installation as it is already installed"
  when: asciidoc_exists is defined

- name: install_libraries | download asciidoc
  get_url: url="{{asciidoc_url}}" dest=/tmp/{{ asciidoc_url | basename }} timeout=120
  when: asciidoc_exists is not defined

- name: install_libraries | unarchive asciidoc tar.gz
  unarchive: src=/tmp/{{ asciidoc_url | basename }} dest=/tmp/ copy=no
  when: asciidoc_exists is not defined

- set_fact: asciidoc_base={{ asciidoc_url | basename }}
  when: asciidoc_exists is not defined

- set_fact: asciidoc_base_dir={{ asciidoc_base | regex_replace('\.tar\.gz','') }}
  when: asciidoc_exists is not defined

- set_fact: asciidoc_base_dir={{ asciidoc_base | regex_replace('\.tgz','') }}
  when: asciidoc_base_dir is not defined and asciidoc_exists is not defined

- name: install_libraries | install asciidoc from src
  sudo: yes
  sudo_user: root
  shell: ./configure ; make && make install;
  args:
   chdir: /tmp/{{ asciidoc_base_dir }}
  when: asciidoc_exists is not defined

- name: install_libraries | rm /tmp/{{ asciidoc_base_dir }}
  sudo: yes
  sudo_user: root
  shell: rm -rf /tmp/{{ asciidoc_base_dir }}*
  when: asciidoc_exists is not defined
