---
- name: install_double-conversion | check if double-conversion is installed
  stat:
    path: "{{ hbase_native_home }}/lib/libdouble-conversion.so"
  register: stat_result

- name: install_double-conversion | set fact false if double-conversion is not installed
  set_fact:
    double_conversion_exists: false
  when: stat_result.stat.exists == False

- name: install_double-conversion | set fact true if double-conversion is installed
  set_fact:
    double_conversion_exists: true
  when: stat_result.stat.exists == True

- name: install_double-conversion | skip double-conversion installation
  debug: msg="skipping double-conversion installation as it is already installed"
  when: double_conversion_exists

- name: install_double-conversion | download double-conversion
  get_url: url="{{double_conversion_url}}" dest=/tmp/{{ double_conversion_url | basename }} timeout=120
  when: not double_conversion_exists

- name: install_double-conversion | unarchive double-conversion tar.gz
  unarchive: src=/tmp/{{ double_conversion_url | basename }} dest=/tmp/ copy=no
  when: not double_conversion_exists

- name: install_double-conversion | install double-conversion from src
  shell: mkdir build; cd build; cmake .. -DCMAKE_INSTALL_PREFIX={{hbase_native_home}} -DBUILD_SHARED_LIBS=ON ; make; make install;
  args:
   chdir: /tmp/double-conversion-{{double_conversion_version}}
  when: not double_conversion_exists and ansible_os_family != 'RedHat'

- name: install_double-conversion | install double-conversion from src
  shell: scl enable devtoolset-6 "mkdir build; cd build; cmake .. -DCMAKE_INSTALL_PREFIX={{hbase_native_home}} -DBUILD_SHARED_LIBS=ON ; make; make install;"
  args:
   chdir: /tmp/double-conversion-{{double_conversion_version}}
  when: not double_conversion_exists and ansible_os_family == 'RedHat'

- name: install_double-conversion | rm /tmp/double-conversion-{{double_conversion_version}}
  sudo: yes
  sudo_user: root
  shell: rm -rf /tmp/double-conversion-{{double_conversion_version}}
  when: not double_conversion_exists

- name: install_double-conversion | rm /tmp/{{ double_conversion_url | basename }}
  sudo: yes
  sudo_user: root
  shell: rm -rf /tmp/{{ double_conversion_url | basename }}
  when: not double_conversion_exists
