---
  - name: install_protobuf | Download protobuf
    get_url: url={{protobuf_url}} dest=/tmp/{{ protobuf_url | basename }}

  - name: install_protobuf | rm protobuf
    shell: rm -rf /usr/local/bin/protoc

  - name: install_protobuf | untar Protobuf
    unarchive: copy=no src=/tmp/{{ protobuf_url | basename }} dest=/tmp/

  - name: install_protobuf | configure/make/make install
    sudo: yes
    sudo_user: root
    shell: cd /tmp/protobuf-2.5.0 ; ./configure --prefix=/opt ; make clean ; make install
