---
  - name: install_protobuf | Download protobuf
    get_url: url={{protobuf_url}} dest=/tmp/protobuf.tar.gz     

  - name: install_protobuf | rm protobuf
    shell: rm -rf /usr/local/bin/protoc

  - name: install_protobuf | untar Protobuf
    unarchive: copy=no src=/tmp/protobuf.tar.gz dest=/tmp/

  - name: install_protobuf | configure/make/make install
    shell: cd /tmp/protobuf-2.5.0 ; ./configure --prefix=/opt ; make clean ; make install
