---
  - name: install_node_js | check if node_js is installed
    command: /usr/local/bin/npm --version
    register: check_npm
    ignore_errors: yes

  - name: install_node_js | check if node_js is installed
    command: /usr/local/bin/node --version
    register: check_node
    ignore_errors: yes

  # check if "check_node_js" is defined and value is equal to desired node_js version
  - name: install_node_js | "set fact if npm version is 1.4.9 and node version is 0.10.28"
    set_fact: npm_exists="true"
    when: (check_npm.rc == 0 and check_npm.stdout.find('1.4.9') != -1) and (check_node.rc == 0 and check_node.stdout.find('0.10.28') != -1)

  - name: install_node_js | skip node_js installation
    debug: msg="skip node_js installation as it is already installed"
    when: npm_exists is defined

  - name: install_node_js | Download node js
    get_url: url={{node_js_url}} dest=/tmp/{{ node_js_url | basename }} timeout=120
    when: npm_exists is not defined

  - name: install_node_js | rm /usr/local/bin/{npm,node} 
    shell: rm -rf /usr/local/bin/{npm,node} 
    when: npm_exists is not defined

  - name: install_node_js | untar node js
    sudo: yes
    sudo_user: root
    unarchive: copy=no src=/tmp/{{ node_js_url | basename }} dest=/usr/local
    when: npm_exists is not defined

  - name: install_node_js | rm /usr/local/bin/{npm,node} 
    shell: rm -rf /usr/local/bin/{npm,node}
    when: npm_exists is not defined

  - name: install_node_js | symlink node and npm
    sudo: yes
    sudo_user: root
    file: src={{item.src_path}}  dest={{item.dest}} state=link
    with_items:
      - { src_path: '/usr/local/node-v{{node_version}}-linux-x64/bin/npm', dest: '/usr/local/bin/npm' }
      - { src_path: '/usr/local/node-v{{node_version}}-linux-x64/bin/node', dest: '/usr/local/bin/node' }
    when: npm_exists is not defined

  - name: install_node_js | brunch install
    sudo: yes
    sudo_user: root
    shell: /usr/local/bin/npm install -g brunch@1.8.5

  - name: run npm set secure | npm install
    sudo: yes
    sudo_user: "{{ build_user }}"
    command: "/usr/local/bin/npm config set unsafe-perm true"
    tags: npm_config

  - name: run npm set registry | npm install
    sudo: yes
    sudo_user: "{{ build_user }}"
    command: "/usr/local/bin/npm config set registry {{ npm_registry }}"
    tags: npm_config

  - name: run npm set proxy | npm install
    sudo: yes
    sudo_user: "{{ build_user }}"
    command: "/usr/local/bin/npm config set proxy {{ cache_proxy }}"
    tags: npm_config

  - name: run npm set https-proxy | npm install
    sudo: yes
    sudo_user: "{{ build_user }}"
    command: "/usr/local/bin/npm config set https-proxy {{ cache_proxy }}"
    tags: npm_config

  - name: install_node_js | delete node.tar.gz from /tmp
    sudo: yes
    sudo_user: root
    file: path=/tmp/{{ node_js_url | basename }} state=absent