---
- name: install_libraries | download ruby
  get_url: url="{{ruby_url}}" dest=/tmp/{{ ruby_url | basename }}

- name: install_libraries | unarchive ruby tar.gz
  unarchive: src=/tmp/{{ ruby_url | basename }} dest=/tmp/ copy=no

- name: install_libraries | install ruby from src
  sudo: yes
  sudo_user: root
  shell: ./configure ; make -j12; make install;
  args:
   chdir: /tmp/ruby-1.9.3-p484

- name: install_libraries | rm /tmp/ruby-1.9.3-p484
  sudo: yes
  sudo_user: root
  shell: rm -rf /tmp/ruby-1.9.3*
