---
  - name: install_node_js | Download node js
    get_url: url={{node_js_url}} dest=/tmp/{{ node_js_url | basename }}

  - name: install_node_js | rm /usr/local/bin/{npm,node} 
    shell: rm -rf /usr/local/bin/{npm,node} 

  - name: install_node_js | untar node js
    sudo: yes
    sudo_user: root
    unarchive: copy=no src=/tmp/{{ node_js_url | basename }} dest=/usr/local

  - name: install_node_js | rm /usr/local/bin/{npm,node} 
    shell: rm -rf /usr/local/bin/{npm,node}

  - name: install_node_js | symlink node and npm
    sudo: yes
    sudo_user: root
    file: src={{item.src_path}}  dest={{item.dest}} state=link
    with_items:
      - { src_path: '/usr/local/node-v{{node_version}}-linux-x64/bin/npm', dest: '/usr/local/bin/npm' }
      - { src_path: '/usr/local/node-v{{node_version}}-linux-x64/bin/node', dest: '/usr/local/bin/node' }

  - name: install_node_js | brunch install
    sudo: yes
    sudo_user: root
    shell: /usr/local/bin/npm install -g brunch 
