---
  - include: squeeze_repo_setup.yml
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'squeeze'

  - include: debian_install_libraries.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: centos_env_setup.yml
    when: ansible_os_family == 'RedHat'

  - include: centos6_install_libraries.yml
    when: ansible_os_family == 'RedHat' and ansible_lsb.major_release == '6'

  - include: install_protobuf.yml
  - include: install_node_js.yml
  - include: update_ulimit.yml
  - include: install_massageHostname.yml
  - include: install_ruby_libs.yml
  - include: install_python_libs.yml

  - include: centos_env_setup.yml
    when: ansible_os_family == 'RedHat'

  - include: replace_gpg_key.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
