---
  - include: squeeze_repo_setup.yml
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'squeeze'

  - include: debian_install_libraries.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: sles11sp3_setup_env.yml
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11' and ansible_distribution_release == '3'

  - include: sles11sp1_setup_env.yml
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11' and ansible_distribution_release == '1'

  - include: sles11_install_libraries.yml
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11' and ansible_distribution_release == '1' or ansible_distribution_release == '3'

  - include: centos_env_setup.yml
    when: ansible_os_family == 'RedHat'

  - include: centos_install_libraries.yml
    when: ansible_os_family == 'RedHat'

  - include: centos5_install_libraries.yml
    when: ansible_os_family == 'RedHat' and ansible_lsb.major_release == '5'

  - include: centos5_install_tar.yml
    when: ansible_os_family == 'RedHat' and ansible_lsb.major_release == '5'

  - include: install_protobuf.yml
  - include: install_node_js.yml
  - include: update_ulimit.yml
  - include: install_massageHostname.yml
  - include: install_ruby_libs.yml
  - include: install_python_libs.yml

  - include: centos_env_setup.yml
    when: ansible_os_family == 'RedHat'

  - include: replace_gpg_key.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: install_python3.yml
    tags: try
