---
  - include: squeeze_repo_setup.yml
    tags: debian_repo_setup
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'squeeze'

  - include: debian_install_libraries.yml
    tags:
      - install_libraries
      - debian_libraries
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: sles11sp3_setup_env.yml
    tags: install_libraries
    when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '3'

  - include: sles11sp3_install_libraries.yml
    tags: install_libraries
    when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '3'

  - include: install_openssl1.yml
    tags: install_openssl1
    when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '3'

  - include: sles11sp1_setup_env.yml
    tags: install_libraries
    when: ansible_distribution == 'SLES' and ansible_distribution_major_version == '11' and ansible_distribution_release|int == 1

  - include: sles11_install_libraries.yml
    tags: install_libraries
    when: (ansible_distribution == 'Suse' or  ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '1' or ansible_distribution_release == '3'

  - include: sles11sp1_install_libraries.yml
    tags: install_libraries
    when: (ansible_distribution == 'Suse' or  ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '1'

  - include: configure_clamav.yml
    tags: configure_clamav
    when: (ansible_distribution == 'Suse' or  ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '1' or ansible_distribution_release == '3'

  - include: centos_env_setup.yml
    tags: centos_rpm_gpg
    when: project != "dev" and ansible_os_family == 'RedHat'

  - include: centos_install_libraries.yml
    tags: install_libraries
    when: ansible_os_family == 'RedHat'

  - include: centos5_install_libraries.yml
    tags: install_libraries
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 5

  - include: install_r.yml
    tags: install_r
    when: ( ansible_distribution != 'Suse' and ansible_distribution != 'SLES' )

  - include: centos6_install_libraries.yml
    tags:
      - install_libraries
      - centos6_libraries
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version != '5'

  - include: install_git.yml
    tags: install_git

  - include: install_protobuf.yml
    tags: install_protobuf

  - include: install_ruby.yml
    tags: install_ruby

  - include: install_autoconf.yml
    tags: install_autoconf

  - include: install_node_js.yml
    tags: install_nodejs

  - include: update_ulimit.yml
    tags: update_ulimit

  - include: install_ruby_libs.yml
    tags: install_ruby

  - include: install_python_libs.yml
    tags:
      - install_python
      - pip_conf

  - include: install_python27.yml
    tags:
      - install_python27
      - install_python

  - include: install_python3.yml
    tags:
      - install_python3
      - install_python

  - include: install_ansible.yml
    tags: install_ansible

  - include: replace_gpg_key.yml
    tags: replace_gpg_key
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' and project != "dev"

  - include: centos5_install_tar.yml
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 5

  - include: install_asciidoc.yml
    tags: install_asciidoc
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: install_awscli.yml
    tags: install_awscli
    when: project != "dev"

  - include: devci_profiles.yml
    tags: devci_profiles
    when: project == "re"

  - include: install_fortify_sca.yml
    tags: fortify_sca

#  - include: install_zinc.yml
#    tags: install_zinc
