  - name: install_libraries | install HDP-utils zypper repo 
    sudo: yes
    zypper_repository: name="HDP-UTILS" repo="http://s3.amazonaws.com/dev.hortonworks.com/HDP-UTILS-1.1.0.17/repos/suse11" state=present

  - name: Installing Libraries | suse11sp3
    sudo: yes
    when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '3'
    zypper: pkg={{item}} disable_gpg_check=yes state=latest
    with_items:
      - gcc
      - gcc43
      - gcc43-c++
      - git

  - name: install gcc-c++ | suse11sp3
    sudo: yes
    sudo_user: root
    when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '3'
    get_url: url="http://dev.hortonworks.com.s3.amazonaws.com/ARTIFACTS/suse11sp3/gcc-suse11sp3.tar.gz" dest=/tmp/gcc-suse11sp3.tar.gz

  - name: install gcc-c++ | suse11sp3
    sudo: yes
    sudo_user: root
    when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '3'
    unarchive: copy=no src=/tmp/gcc-suse11sp3.tar.gz dest=/tmp/

  - name: install gcc-c++ | suse11sp3
    sudo: yes
    sudo_user: root
    when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '3'
    shell: rpm -ivh {{item}}
    register: shell_result
    with_items:
      - /tmp/gcc-suse11sp3/gcc-c++-4.3-62.12.x86_64.rpm

  - name: Installing Libraries | sles11sp1
    sudo: yes
    when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '1'
    zypper: pkg=gcc-c++ disable_gpg_check=yes state=latest

  - name: "Installing Libraries"
    sudo: yes
    zypper: pkg={{item}} disable_gpg_check=yes state=installed
    with_items:
      - clamav
      - createrepo
      - wget
      - lsb-release
      - curl
      - subversion
      - snappy-devel
      - lzo-devel
      - asciidoc
      - libcppunit-devel
      - gcc
      - automake
      - autoconf
      - libconfuse-devel
      - ant
      - ant-nodeps
      - ant-trax
      - cmake
      - fuse-devel
      - docbook-utils
      - python-devel
      - python-setuptools
      - libxml2-devel
      - libxslt-devel
      - krb5-devel
      - sqlite3-devel
      - gd-devel
      - libpng-devel
      - libjpeg-devel
      - cairo-devel
      - freetype2-devel
      - glib2-devel
      - docbook-xsl-stylesheets
      - xmlformat
      - texlive-latex
      - intltool
      - pango-devel
      - gettext-tools
      - ruby-devel
      - lua-devel
      - tcpd-devel
      - dejagnu
      - rsh
      - xorg-x11-devel
      - fdupes
      - tcl-devel
      - libconfuse-devel
      - rrdtool-devel
      - latex2html-pngicons
      - clamav
      - docbook-xsl-stylesheets
      - docbook
      - texlive-latex-doc
      - texlive-latex
      - xmlformat
      - xmlto
      - libtool
      - libxslt
      - pcre-devel
      - docbook5-xsl-stylesheets
      - docbook-utils
      - libart_lgpl-devel

  - name: install_libraries | zypper in
    sudo: yes
    shell: rpm -Uvh {{item}} 
    register: shell_result
    with_items:
      - http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/suse11sp3/googletest-1.7.0-16.1.x86_64.rpm
      - http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/suse11sp3/googletest-devel-1.7.0-16.1.x86_64.rpm
      - http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/suse11sp3/asciidoc-8.6.8-8.1.noarch.rpm
      - http://s3tools.org/repo/SLE_11/x86_64/s3cmd-1.0.0-4.1.x86_64.rpm
    tags: install_libraries
    ignore_errors: true
