- name: Create a set of VMs ready to run Hortonworks tests.
  hosts: localhost
  gather_facts: true
  vars:
    BUILD_USER_ID:   jabowles
    instance_type: m3.xlarge
    security_group: RE-JENKINS-SLAVES
    image: ami-5041b138
    keypair: ec2-keypair
    region: us-east-1
    currentTime: "{{ ansible_date_time.epoch }}"
    lifetime: "{{ lookup('env','LIFETIME') }}"
  tags: createInstances
  tasks:
    - name: check-host-keys
      fail:  msg="You must set $ANSIBLE_HOST_KEY_CHECKING=false before running."
      when:  lookup('env', 'ANSIBLE_HOST_KEY_CHECKING')  != 'false'
    - name: check-host-keys
      debug:  msg="Thank you for setting $ANSIBLE_HOST_KEY_CHECKING=false"
      when:  lookup('env', 'ANSIBLE_HOST_KEY_CHECKING') == 'false'
    - name: Launch instance
      register: ec2
      local_action:
         module: ec2
         key_name: "{{ keypair }}"
         instance_type: "{{instance_type}}"
         image: "{{ image }}"
         assign_public_ip: yes
         vpc_subnet_id: subnet-dc11f9ab
         wait: yes
         group: "{{ security_group }}"
         region: "{{ region }}"
         count: 8
         instance_tags:
            Name: "c64-xx"
            User: "{{ BUILD_USER_ID }}"
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=6 timeout=1200 state=started
      with_items: ec2.instances
    - name: Write out host-names, external
      lineinfile: line="{{item.public_ip}} {{item.public_dns_name}}" dest={{lookup("env","PWD")}}/hosts-file state=present  create=yes insertafter=EOF
      with_items: ec2.instances
    - name: Write out host-names, external
      lineinfile: line="{{item.private_ip}} {{item.public_dns_name}}" dest={{lookup("env","PWD")}}/internal-hosts-file state=present  create=yes insertafter=EOF
      with_items: ec2.instances

- hosts: launched
  gather_facts: no
  vars:
    jenkins_user_uid: 1001
    slave: False
    jenkins_user: jenkins
    jenkins_group: users
    jenkins_configuration: /etc/default/jenkins
    jenkins_run_standalone: yes
    jenkins_name: jenkins
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "{{lookup('env','HOME')}}/.ssh/ec2-keypair.pem"

  roles:
    - centos6-slaves
