- name: Create a set of VMs ready to run Hortonworks tests.
  hosts: localhost
  gather_facts: true
  vars:
    BUILD_USER_ID:   "{{lookup('env', 'USER')}}"
    instance_type: m1.medium
    security_group: RE-JENKINS-SLAVES
    ami: default
    count: 1
    keypair: ext-keypair
    region: us-east-1
    currentTime: "{{ ansible_date_time.epoch }}"
    lifetime: "{{ lookup('env','LIFETIME') }}"
  tags: createInstances
  tasks:
    - name: check-host-keys
      fail:  msg="You must set $ANSIBLE_HOST_KEY_CHECKING=false before running."
      when:  lookup('env', 'ANSIBLE_HOST_KEY_CHECKING')  != 'false'
    - name: check-host-keys
      debug:  msg="Thank you for setting $ANSIBLE_HOST_KEY_CHECKING=false"
      when:  lookup('env', 'ANSIBLE_HOST_KEY_CHECKING') == 'false'
    - name: debug-ami 
      fail:  msg="try running with -e ami=ami-b61ae1de for a default AMI"
      when: ami == "default"
    - name: Launch instance
      register: ec2
      local_action:
         module: ec2
         key_name: "{{ keypair }}"
         instance_type: "{{instance_type}}"
         image: "{{ ami }}"
         assign_public_ip: yes
         vpc_subnet_id: subnet-dc11f9ab
         wait: yes
         group: "{{ security_group }}"
         region: "{{ region }}"
         count: "{{count}}"
         instance_tags:
            User: "{{ BUILD_USER_ID }}"
            StartTime: "{{ currentTime }}"
            LifetimeInHrs:  "{{ lifetime }}"
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=6 timeout=320 state=started
      with_items: ec2.instances
    - name: Write out host-names, external
      lineinfile: line="{{item.public_ip}} {{item.public_dns_name}}" dest={{lookup("env","PWD")}}/hosts-file state=present  create=yes insertafter=EOF
      with_items: ec2.instances
    - name: Write out host-names, external
      lineinfile: line="{{item.private_ip}} {{item.public_dns_name}}" dest={{lookup("env","PWD")}}/internal-hosts-file state=present  create=yes insertafter=EOF
      with_items: ec2.instances

- hosts: launched
  gather_facts: no
  vars:
     ansible_ssh_user: ec2-user
     ansible_ssh_private_key_file: "{{lookup('env','WORKSPACE')}/keys/ext-keypair.pem"
     internal_hosts_file: "{{lookup('env','PWD')}}/internal-hosts-file"
     external_hosts_file: "{{lookup('env','PWD')}}/hosts-file"
  roles:
    - centos-systest
