- hosts: centos6
  gather_facts: yes
  vars:
    jenkins_user_uid: 1001
    slave: False
    jenkins_user: jenkins
    jenkins_group: users
    jenkins_configuration: /etc/default/jenkins
    jenkins_run_standalone: yes
    jenkins_name: jenkins
    push_password: false

  roles:
    - common
    - centos6-slaves
