- hosts: debian6
  gather_facts: no
  vars:
    jenkins_user_uid: 1001
    slave: False
    jenkins_user: jenkins
    jenkins_group: users
    jenkins_configuration: /etc/default/jenkins
    jenkins_run_standalone: yes
    jenkins_name: jenkins
    gem2deb_url: http://ftp.de.debian.org/debian/pool/main/g/gem2deb/gem2deb_0.9.1.tar.xz

  roles:
    - common
    - debian6-slaves

