---

aws_access_key
aws_secret_key
- name: ec2_start_instance | debian instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: ec2-keypair
    instance_type: m1.small
    security_group: jenkins-slaves
    image: ami-0740476e
    region: us-east-1
  tasks:
    - name: Launch instance
      local_action: ec2 key_name={{ keypair }} group={{ security_group }} instance_type={{ instance_type }} image={{ image }} wait=true region={{ region }}
      register: ec2
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
