---
- hosts: jenkins-slaves
  vars:
    mvn_version: "3.1.1"
    ant_version: "1.9.4"
    forrest_version: "0.9"
    maven_url: "http://mirror.metrocast.net/apache/maven/maven-3/{{ mvn_version }}/binaries/apache-maven-{{ mvn_version }}-bin.tar.gz"
    ant_url: "http://www.dsgnwrld.com/am//ant/binaries/apache-ant-{{ant_version}}-bin.tar.gz"
    td_repo: "http://s3.amazonaws.com/dev.hortonworks.com/sles11/sles11.repo"
    jdk6_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/jdk6_31.tar.gz"
    jdk7_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/jdk-7u21-linux-x64.gz"
    forrest_url: "http://psg.mtu.edu/pub/apache//forrest/apache-forrest-{{forrest_version}}-sources.tar.gz"
    s3tools_url: "http://s3tools.org/repo/SLE_11/s3tools.repo"
    s3cfg_url: "http://s3.amazonaws.com/dev.hortonworks.com/RLENG/s3cfg"
    settings_url: "http://s3.amazonaws.com/dev.hortonworks.com/jenkins_bk/54.243.248.12/settings.xml"
    gpgkeys_url: "http://s3.amazonaws.com/dev.hortonworks.com/RLENG/jenkins-gpg-keys.tar.gz"
    ssh_url: "http://s3.amazonaws.com/dev.hortonworks.com/RLENG/hortonworksre.tar.gz"
    hdp_utils_url: "http://s3.amazonaws.com/dev.hortonworks.com/HDP-UTILS-1.1.0.17/repos/suse11/hdp-util.repo"
    ssh_url_dest: "{{jenkins_home}}/hortonworksre.tar.gz"
    gpgkey_dest: "{{jenkins_home}}/jenkins-gpg-keys"

    jenkins_home: /home/jenkins
    tools_home: "{{jenkins_home}}/tools"
    maven_home: "{{tools_home}}/maven"
    ant_home: "{{tools_home}}/ant" 
    jdk6_home: "{{tools_home}}/jdk64_31"
    jdk7_home: "{{tools_home}}/jdk7"
    forrest_home: "{{tools_home}}/forrest"

  tasks:
    - include: tasks/setup_user.yml
    - include: tasks/install_tools.yml
    - include: tasks/install_jdk.yml
    - include: tasks/update_configs.yml
    - include: tasks/install_libraries.yml

