- hosts: openstack
  gather_facts: yes
  vars:
    sensu_server: false
    sensu_client: true
    sensu_master_host: 172.22.68.66
    datacentername: "Openstack"
    sensu_password: xpassword
    admin_password: secret
    defaultsubscription: openstack
  roles:
    - sensu
