- hosts: openstack
  vars:
    sensu_server: false
    sensu_client: true
    sensu_master_host: 172.22.69.206
    datacentername: "Openstack"
    sensu_password: xpassword
    defaultsubscription: jenkins-slaves

  roles:
    - sensu
