- hosts: openstack
  gather_facts: yes
  vars:
    sensu_server: true
    sensu_client: true
    sensu_master_host: sensu.eng.hortonworks.com
    datacentername: "Openstack"
    sensu_password: xpassword
    admin_password: secret
    slack_webhook_url: https://hooks.slack.com/services/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
    hipchat_api_token: bicPTrQ2eLagahHfBwi7zPKaGeOeFMB2waU6J5ZT
    defaultsubscription: all

  roles:
    - sensu
