- hosts: sles11sp3
  gather_facts: no
  vars:
    jenkins_user_uid: 1001
    slave: False
    jenkins_user: jenkins
    jenkins_group: users
    jenkins_configuration: /etc/default/jenkins
    jenkins_run_standalone: yes
    jenkins_name: jenkins
    push_password: false
    gpg_file: ~/password_gpg.txt
    nexus_file: ~/nexus_password.txt
    security_file: ~/settings-security.xml
    ec2_hostname: False

  roles:
    - common
    - sles11sp3-slaves
