- name: Create a set of VMs ready to run Hortonworks tests.
  hosts: windows
  gather_facts: true
  vars:
    JenkinsAPIKEY:   "{{lookup('env', 'JENKINSAPIKEY')}}"
    makelevel2: false
  tags: initialsetupExample
  tasks:
  - name: check-api-keys
    fail:  msg="You must set $JENKINSAPIKEY=false before running."
    when:  lookup('env', 'JENKINSAPIKEY')  == ''
  - win_stat: path='C:\horton'
    register: file_info
  - debug: var=file_info

  - win_stat: path='c:\horton'
    register: hortonstats
  - raw: mkdir c:\horton
    when:  not hortonstats.stat.exists

  - win_stat: path='C:\Users\Jenkins\.m2'
    register: m2stats
    tags: mkm2
  - raw: mkdir c:\Users\Jenkins\.m2
    when:  not m2stats.stat.exists
    tags: mkm2
  
  - win_stat: path='c:\temp'
    register: tempoutput
  - debug: var=tempoutput
  - raw: mkdir c:\temp
    when:  not tempoutput.stat.exists

# # Install git
  # - name: chocolate
    # tags: chocolate
    # win_chocolatey: package=git

  - win_stat:  path='c:\temp\Git-1.9.5-preview20141217.exe'
    tags: installgit
    register:  filestat
  - name: retrieve file
    tags: installgit
    win_get_url:  url='https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20141217/Git-1.9.5-preview20141217.exe' dest='c:\temp\Git-1.9.5-preview20141217.exe'
    when: not filestat.stat.exists


  - win_stat:  path='c:\temp\apache-ant-1.7.1-bin.zip'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/apache-ant-1.7.1-bin.zip' dest='c:\temp\apache-ant-1.7.1-bin.zip'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\apache-ant-1.8.3-bin.zip'
    tags: installants
    register:  filestat
  - name: retrieve file
    tags: installants
    win_get_url:  url='http://archive.apache.org/dist/ant/binaries/apache-ant-1.8.3-bin.zip' dest='c:\temp\apache-ant-1.8.3-bin.zip'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\apache-forrest-0.8.zip'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/apache-forrest-0.8.zip' dest='c:\temp\apache-forrest-0.8.zip'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\coreutils-5.3.0.exe'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/coreutils-5.3.0.exe' dest='c:\temp\coreutils-5.3.0.exe'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\diffutils-2.8.7-1.exe'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/diffutils-2.8.7-1.exe' dest='c:\temp\diffutils-2.8.7-1.exe'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\jdk-6-builds-maven-settings.xml'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/jdk-6-builds-maven-settings.xml' dest='c:\temp\jdk-6-builds-maven-settings.xml'
    # when: not filestat.stat.exists

  - win_stat:  path='C:\horton\java\jdk1.6.0_35'
    tags: installjdk6
    register:  filestat
  - name: retrieve file
    tags: installjdk6
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/jdk-6u35-windows-x64.exe' dest='c:\temp\jdk-6u35-windows-x64.exe'
    when: not filestat.stat.exists
  - raw:  c:\temp\jdk-6u35-windows-x64.exe /qn /norestart /log jdk-6u35-windows-x64.log  INSTALLDIR=C:\horton\java\jdk1.6.0_35
    tags: installjdk6
    register: file_info
    when:  not filestat.stat.exists
  - debug: var=file_info
    tags: installjdk6

  - win_stat:  path='c:\users\jenkins\.ssh\id_rsa'
    register:  idrsastat
  - raw: mkdir c:\users\adminstrators\.ssh
    when:  not idrsastat.stat.exists
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/jdk-7-builds-maven-settings.xml' dest='c:\temp\jdk-7-builds-maven-settings.xml'
    when: not idrsastat.stat.exists

  - win_stat:  path='c:\temp\jdk-7-builds-maven-settings.xml'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/jdk-7-builds-maven-settings.xml' dest='c:\temp\jdk-7-builds-maven-settings.xml'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\jdk-7-windows-x64.exe'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/jdk-7-windows-x64.exe' dest='c:\temp\jdk-7-windows-x64.exe'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\jdk-7u12-ea-bin-b05-windows-x64-12_dec_2012.exe'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/jdk-7u12-ea-bin-b05-windows-x64-12_dec_2012.exe' dest='c:\temp\jdk-7u12-ea-bin-b05-windows-x64-12_dec_2012.exe'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\openjdk7-Mahadevan.zip'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/openjdk7-Mahadevan.zip' dest='c:\temp\openjdk7-Mahadevan.zip'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\publicpreview-ms5-maven-settings.xml'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/publicpreview-ms5-maven-settings.xml' dest='c:\temp\publicpreview-ms5-maven-settings.xml'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\rubyinstaller-1.9.3-p327.exe'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/rubyinstaller-1.9.3-p327.exe' dest='c:\temp\rubyinstaller-1.9.3-p327.exe'
    when: not filestat.stat.exists

  - win_stat:  path='c:\temp\which-2.20-setup.exe'
    register:  filestat
  - name: retrieve file
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/which-2.20-setup.exe' dest='c:\temp\which-2.20-setup.exe'
    when: not filestat.stat.exists

  - name: retrieve file
    tags: installants
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/extract-zip.ps1' dest='c:\temp\extract-zip.ps1' force=yes
    tags: installants
    register: file_info
  - debug: var=file_info
    tags: installants

  - win_stat: path='c:\horton\git'
    register: gitstat
  - debug: var=gitstat
  - raw: c:\temp\Git-1.9.5-preview20141217.exe /verysilent /log=Git-1.9.5-preview20141217.log /SAVEINF=Git-1.9.5-preview20141217.inf /NORESTART /SP- /SUPPRESSMSGBOXES /DIR=C:\horton\git
    tags: installgit
    register: file_info
    # when:  not gitstat.stat.exists
  - debug: var=file_info

  - win_stat:  path='c:\horton\cygwin-1.7'
    tags: installcygwin
    register:  filestat
  - name: retrieve cygwin-1.7
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/cygwin-1.7.zip' dest='c:\temp\cygwin-1.7.zip'
    tags: installcygwin
    when: not filestat.stat.exists
  - name: install cygwin-1.7
    tags: installcygwin
    raw:  c:\horton\git\bin\unzip -o c:\temp\cygwin-1.7.zip -d c:\horton\
    when: not filestat.stat.exists

  #  # commenting out winsdk7.1 for the moment. Might be an ordering problem, etc. But it's saying that it cannot find some .msi files.
  #  - win_stat:  path='c:\temp\winsdk7.1'
  #    tags: installwinsdk
  #    register:  filestat
  #  - name: retrieve winsdk7.1.zip
  #    tags: installwinsdk
  #    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/winsdk7.1.zip' dest='c:\temp\winsdk7.1.zip'
  #    tags: installwinsdk
  #    when: not filestat.stat.exists
  #  - name: install winsdk-7.1
  #    tags: installwinsdk
  #    raw:  c:\horton\git\bin\unzip  -o c:\temp\winsdk7.1.zip -d c:\temp\
  #    # when: not filestat.stat.exists
  #  - name: install winsdk-7.1
  #    tags: installwinsdk
  #    raw:  c:\temp\winsdk7.1\Setup -q -params:ADDLOCAL=ALL
  #    register: mergatroid
  #    # when: not filestat.stat.exists
  #  - name: "Tell what we learned."
  #    tags: installwinsdk
  #    debug: msg="{{mergatroid}}"

  - win_stat: path='c:\horton\tools\apache-ant-1.7.1'
    tags: installants
    register: antstat
  - debug: var=antstat
  - raw: c:\temp\extract-zip.ps1  
    tags: installants
    register: file_info
    when:  not antstat.stat.exists
    # # # # # # # # #  # # # # # when:  not antstat.stat.exists
  - debug: var=file_info
    tags: installants

  - win_stat: path='c:\horton\tools\protoc-2.5.0-win32'
    tags: installprotoc
    register: protoc
  - debug: var=protoc
    tags: installprotoc
  - name: Download protoc
    win_get_url:  url='https://protobuf.googlecode.com/files/protoc-2.5.0-win32.zip' dest='c:\temp\protoc-2.5.0-win32.zip' force=yes
    tags: installprotoc
    when:  not protoc.stat.exists
  - raw: mkdir c:\horton\tools\protoc-2.5.0-win32
    tags: installprotoc
    when:  not protoc.stat.exists
  - raw:  c:\horton\git\bin\unzip -o c:\temp\protoc-2.5.0-win32.zip -d c:\horton\tools\protoc-2.5.0-win32
    tags: installprotoc
    register: file_info
    when:  not protoc.stat.exists
  - debug: var=file_info
    when:  not protoc.stat.exists
    tags: installprotoc

  - win_stat: path='c:\horton\sysinternals'
    tags: installsysinternals
    register: sysinternalsstat
  - debug: var=sysinternalsstat
    tags: installsysinternals
  - name: retrieve sysinternals.zip
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/sysinternals.zip' dest='c:\temp\sysinternals.zip'
    tags: installsysinternals
    # when: not sysinternalsstat.stat.exists
  - raw:  c:\horton\git\bin\unzip -o c:\temp\sysinternals.zip -d c:\horton\
    tags: installsysinternals
    register: file_info
    when:  not sysinternalsstat.stat.exists
  - debug: var=file_info
    tags: installsysinternals

  - win_stat: path='c:\strawberry\perl\bin\perl.exe'
    tags: installperl
    register: perlstat
  - debug: var=perlstat
    tags: installperl
  - name: retrieve perl.zip
    win_get_url:  url='http://strawberryperl.com/download/5.18.4.1/strawberry-perl-5.18.4.1-64bit.msi' dest='c:\temp\strawberry-perl-5.18.4.1-64bit.msi'
    tags: installperl
    when: not perlstat.stat.exists
  - raw:  msiexec  /qn /norestart /log strawberry-perl-5.18.4.1-64bit.log /i c:\temp\strawberry-perl-5.18.4.1-64bit.msi
    tags: installperl
    register: file_info
    when:  not perlstat.stat.exists
  - debug: var=file_info
    tags: installperl

  - win_stat: path='c:\horton\cmake2.8'
    tags: installcmake
    register: cmakestat
  - debug: var=cmakestat
    tags: installcmake
  - name: retrieve cmake installer package
    win_get_url:  url='http://www.cmake.org/files/v2.8/cmake-2.8.9-win32-x86.exe' dest='c:\temp\cmake-2.8.9-win32-x86.exe'
    tags: installcmake
    when: not cmakestat.stat.exists
  - raw: c:\temp\cmake-2.8.9-win32-x86.exe /S /D=C:\horton\cmake2.8
    tags: installcmake
    register: file_info
    when:  not cmakestat.stat.exists
  - debug: var=file_info
    tags: installcmake

  - win_stat: path='c:\horton\tools\apache-maven-3.0.4'
    tags: installmaven
    register: mavenstat
  - debug: var=mavenstat
    tags: installmaven
  - name: retrieve apache-maven-3.0.4.zip
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/apache-maven-3.0.4.zip' dest='c:\temp\apache-maven-3.0.4.zip'
    tags: installmaven
    when: not mavenstat.stat.exists
  - raw:  c:\horton\git\bin\unzip -o c:\temp\apache-maven-3.0.4.zip -d c:\horton\tools\
    tags: installmaven
    register: file_info
    when:  not mavenstat.stat.exists
  - debug: var=file_info
    tags: installmaven

  - win_stat: path='c:horton\java\jdk1.7.0'
    tags: installjdk7
    register: javastat
  - win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/jdk-7-windows-x64.exe' dest='c:\temp\jdk-7-windows-x64.exe'
    tags: installjdk7
    register: file_info
    # when: not javastat.stat.exists
  - debug: var=file_info
    tags: installjdk7
  - raw: c:\temp\jdk-7-windows-x64.exe /qn /norestart /log jdk-7-windows-x64.log  INSTALLDIR=C:\horton\java\jdk1.7.0
    tags: installjdk7
    # when: not javastat.stat.exists


  - name: Set git-config default-email.
    raw: C:\horton\Git\cmd\git config --global user.email "releng-group@hortonworks.com"
    tags: gitconfig
  - name: Set git-config default-username.
    raw: C:\horton\Git\cmd\git config --global user.name "Hortonworks RE"
    tags: gitconfig
  - raw: setx JAVA_HOME c:\horton\Java\jdk1.6.0_35
    tags: setxcommands
  - raw: setx ANT_HOME c:\horton\tools\apache-ant-1.8.3
    tags: installants
    tags: setxcommands
  - raw: setx FORREST_HOME c:\horton\tools\apache-forrest-0.9
    tags: setxcommands

  - name: Set Jenkins auto-boot config
    win_get_url:  url='http://s3.amazonaws.com/dev.hortonworks.com/tools/Win-Build-Slave-Setup/Run-Jenkins.cmd'  dest='c:\users\jenkins\Run-Jenkins.cmd' force=yes
    tags: jenkinsconfig
  - name: Disable Administator auto-boot script.
    raw:  echo > "c:\users\administrator\Run-Jenkins.cmd"
    tags: jenkinsconfig
  - name: Get Jenkins auto-boot .jar files.
    win_get_url:  url='http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/1.22/swarm-client-1.22-jar-with-dependencies.jar'   dest='c:\users\jenkins\Downloads\swarm-client-1.22-jar-with-dependencies.jar' force=yes
    tags: jenkinsconfig
  - raw: echo  set JSTART_URL=http://54.174.81.19:8080/ > "c:\horton\jenkins-env.cmd"
    tags: jenkinsenv
  - raw: echo set JSTART_USER=jabowles >> "c:\horton\jenkins-env.cmd"
    tags: jenkinsenv
  - raw: echo set JSTART_PASSWORD={{JenkinsAPIKEY}} >> "c:\horton\jenkins-env.cmd"
    tags: jenkinsenv
  - raw: echo set LABEL=win-UT >> c:\horton\jenkins-env.cmd
    tags: jenkinsenv
    when: not makelevel2
  - raw: echo set LABEL=win-builds >> c:\horton\jenkins-env.cmd
    when: makelevel2
    tags: jenkinsenv
  - name: Add jenkins to Users group
    raw: net localgroup  Administrators jenkins /add
    when: makelevel2
    tags: jenkinsenv
