- name: Install_Libraries | Install Debian Libraries and build Tools
  sudo: yes
  sudo_user: root
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
      - ant
      - asciidoc
      - autoconf
      - automake
      - bison
      - build-essential
      - cabal-install
      - cmake
      - curl
      - dh-make
      - debhelper
      - devscripts
      - erlang-base
      - erlang-eunit
      - erlang-dev
      - flex
      - g++
      - g++-multilib
      - gcc-multilib
      - ghc
      - git-core
      - lib32z1
      - lib32ncurses5
      - lib32bz2-1.0
      - libbit-vector-perl
      - libboost-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libc6-dev-i386
      - libclass-accessor-class-perl
      - libcppunit-dev
      - libcurl4-nss-dev
      - libcurl4-openssl-dev
      - libevent-dev
      - libfuse-dev
      - libghc-binary-dev
      - libghc-hashable-dev
      - libghc-http-dev
      - libghc-network-dev
      - libghc-unordered-containers-dev
      - libghc-vector-dev
      - libglib2.0-dev
      - libjpeg8-dev
      - liblzo2-dev
      - libmono-system-web2.0-cil
      - libqt4-dev
      - libsasl2-dev
      - libsnappy-dev
      - libssl-dev
      - libtool
      - libxml-xpath-perl
      - libz-dev
      - lua5.2
      - lua5.2-dev
      - mingw32
      - mingw32-binutils
      - mingw32-runtime
      - nodejs
      - nodejs-dev
      - npm
      - mono-devel
      - mono-gmcs
      - php5
      - php5-cli
      - php5-dev
      - php-pear
      - pkg-config
      - protobuf-compiler
      - python-all
      - python-all-dev
      - python-all-dbg
      - python-boto
      - python-dev
      - python-setuptools
      - python-support
      - re2c
      - ruby
      - ruby-dev
      - sharutils
      - g++-4.8-multilib
      - libstdc++-4.8-dev
