---
jenkins_user_uid: 1000
home_base_dir: /grid/0
jenkins_home: "{{home_base_dir}}/jenkins"
tools_home: "{{jenkins_home}}/tools"
maven_home: "{{tools_home}}/maven"
ant_home: "{{tools_home}}/ant" 
jdk6_home: "{{tools_home}}/jdk64_31"
jdk7_home: "{{tools_home}}/jdk7"
forrest_home: "{{tools_home}}/forrest"

mvn_version: "3.1.1"
mvn_ambari_version: "3.0.5"
ant_version: "1.9.4"
forrest_version: "0.9"
node_version: "0.10.28"
utils_version: "1.1.0.17"

maven_url: "http://mirror.metrocast.net/apache/maven/maven-3/{{ mvn_version }}/binaries/apache-maven-{{ mvn_version }}-bin.tar.gz"
maven_ambari_url: "http://mirror.metrocast.net/apache/maven/maven-3/{{ mvn_ambari_version }}/binaries/apache-maven-{{ mvn_ambari_version }}-bin.tar.gz"
ant_url: "http://mirror.cc.columbia.edu/pub/software/apache//ant/binaries/apache-ant-{{ant_version}}-bin.tar.gz"
td_repo: "http://s3.amazonaws.com/dev.hortonworks.com/sles11/sles11.repo"
jdk6_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/jdk6_31.tar.gz"
jdk7_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/jdk-7u21-linux-x64.gz"
forrest_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/apache-forrest-{{forrest_version}}-sources.tar.gz"
protobuf_url: "https://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz"
autoconf_url: "http://ftp.gnu.org/gnu/autoconf/autoconf-2.63.tar.gz"
node_js_url: "http://nodejs.org/dist/v{{node_version}}/node-v{{node_version}}-linux-x64.tar.gz"
s3cfg_url: "http://s3.amazonaws.com/dev.hortonworks.com/RLENG/s3cfg"
ssh_url: "http://s3.amazonaws.com/dev.hortonworks.com/RLENG/hortonworksre.tar.gz"
gpgkeys_url: "http://s3.amazonaws.com/dev.hortonworks.com/RLENG/jenkins-gpg-keys.tar.gz"
settings_url: "http://s3.amazonaws.com/dev.hortonworks.com/jenkins_bk/54.243.248.12/settings.xml"
ssh_url_dest: "{{jenkins_home}}/hortonworksre.tar.gz"
gpgkey_dest: "{{jenkins_home}}/jenkins-gpg-keys"


