---
home_base_dir: /grid/0
build_user_home: "{{home_base_dir}}/{{ build_user }}"
tools_home: "{{build_user_home}}/tools"
maven_home: "{{tools_home}}/maven"
ant_home: "{{tools_home}}/ant" 
jdk6_home: "{{tools_home}}/jdk64_31"
jdk7_home: "{{tools_home}}/jdk7"
jdk7_80_home: "{{tools_home}}/jdk7"
jdk8_home: "{{tools_home}}/jdk8"
forrest_home: "{{tools_home}}/forrest"

mvn_version: "3.1.1"
mvn_ambari_version: "3.0.5"
mvn333_version: "3.3.3"
mvn339_version: "3.3.9"
ant_version: "1.9.4"
forrest_version: "0.9"
node_version: "0.10.28"
utils_version: "1.1.0.17"
ant_old_version: "1.8.2"
jdk8_version: "1.8.0_91"
jdk7_version: "1.7.0_21"
jdk7_80_version: "1.7.0_80"
jdk6_version: "1.6.0_31"
git_version: "2.4.6"
asciidoc_version: "8.6.9"
r_version: "3.2.2"
zinc_version: "0.3.9"
hdpchanges_version: "0.2.0"

maven_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/apache-maven-{{ mvn_version }}-bin.tar.gz"
maven_ambari_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/apache-maven-{{ mvn_ambari_version }}-bin.tar.gz"
maven333_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/apache-maven-3.3.3-bin.tar.gz"
maven339_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/apache-maven-3.3.9-bin.tar.gz"
ant_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/apache-ant-{{ant_version}}-bin.tar.gz"
ant_old_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/apache-ant-{{ant_old_version}}-bin.tar.gz"
td_repo: "http://s3.amazonaws.com/dev.hortonworks.com/sles11/sles11.repo"
jdk6_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/jdk6_31.tar.gz"
jdk7_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/jdk-7u21-linux-x64.gz"
jdk7_80_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/jdk-7u80-linux-x64.tar.gz"
jdk8_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/jdk-8u91-linux-x64.tar.gz"
forrest_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/apache-forrest-{{forrest_version}}-sources.tar.gz"
forrest_dependency_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/apache-forrest-{{forrest_version}}-dependencies.tar.gz"
protobuf_url: "http://dev.hortonworks.com.s3.amazonaws.com/ARTIFACTS/protobuf-2.5.0.tar.gz"
autoconf_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/autoconf-2.63.tar.gz"
node_js_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/node-v{{node_version}}-linux-x64.tar.gz"
ruby_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/ruby-1.9.3-p484.tar.gz"
ant_contrib_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/ant-contrib-1.0b2.jar"
eclipse_url: "http://dev.hortonworks.com.s3.amazonaws.com/REJENKINS/eclipse.tar.gz"
xerces_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/xerces-c.tar.gz"
git_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/git-2.4.6.tar.gz"
curl_url: "http://dev.hortonworks.com.s3.amazonaws.com/REJENKINS/sles11sp1/curl-7.43.0.tar.gz"
asciidoc_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/asciidoc-8.6.9.tar.gz"
sonar_ant_task_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/sonar-ant-task-2.3.jar"
sonar_runner_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/sonar-runner-dist-2.4.zip"
r_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/R-3.2.2.tar.gz"
zinc_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/zinc-{{ zinc_version }}.tgz"
npm_registry: "http://registry.npmjs.org/"
cache_proxy: "http://hwx-eng:5XD6xKQDiKDjOD@buildcache.eng.hortonworks.com:1280"
hdpchanges_url: "http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/hdpchanges/{{hdpchanges_version}}/hdpchanges"
