---
  - name: "Install suse11 TD repo"
    get_url: url={{ td_repo }} dest=/etc/zypp/repos.d/sles11.repo

  - name: "Install s3tools repo"
    get_url: url={{ s3tools_url }} dest=/etc/zypp/repos.d/s3tools.repo

  - name: "Install s3tools repo"
    get_url: url={{ hdp_utils_url }} dest=/etc/zypp/repos.d/hdp-util.repo

  - name: "Installing Libraries"
    sudo: yes
    sudo_user: root
    zypper: pkg={{item}} disable_gpg_check=yes state=latest
    with_items:
      - s3cmd
      - subversion
      - snappy-devel
      - lzo-devel
      - asciidoc
      - libcppunit-devel
      - git-core
      - gcc
      - gcc-c++
      - automake 
      - autoconf
      - libconfuse-devel
      - fuse-devel
      - docbook-utils 
      - docbook5-xsl-stylesheets
      - xmlformat
      - xmlto 
      - libxslt
      - libopenssl-devel
      - docbook_5


