---
 - name: install_mysql | Yum install Mysql packages
   yum: "name={{item}} state=installed"
   with_items:
   - mysql-server
   - mysql
   register: mysql_install_packages

 - name: check selinux status
   shell: sestatus | awk ' { print $NF }'
   register: selinux_status

 - name: disable selinux temporarily
   shell : echo 0 > /selinux/enforce
   when: selinux_status.stdout == "enabled"

 - name: disable selinux to persist after a reboot
   replace:
    path: /etc/sysconfig/selinux
    regexp: '^SELINUX=enabled$'
    replace: 'SELINUX=disabled'
   when: selinux_status.stdout == "enabled"

 - name: check if mysql packages are installed
   set_fact:
     installed_mysql_packages: "{{ (mysql_install_packages is defined and mysql_install_packages.changed) }}"

