---
  - name: setup_user | ssh keys - Download
    become: yes
    become_user: "{{ build_user }}"
    when: project != 'dev'
    get_url: url={{ ssh_url }} dest={{build_user_home}}/{{ ssh_url | basename }}

  - name: setup_user | ssh keys - Download
    become: yes
    become_user: "{{ build_user }}"
    when: project == 'dev'
    copy: src={{ ssh_url }} dest={{build_user_home}}/{{ ssh_url | basename }} owner={{ build_user }}  group={{ build_group }} mode=0644

  - name: setup_user | ssh keys - untar
    become: yes
    become_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ ssh_url | basename }} dest={{build_user_home}}/

  - set_fact: base_ssh_url="{{ ssh_url | basename }}"
  - set_fact: base_ssh_dir="{{ base_ssh_url.split('.')[0] }}"

  - name: setup_user | create ssh directory
    become: yes
    become_user: "{{ build_user }}"
    file: path={{build_user_home}}/.ssh state=directory mode=700

  - name: setup_user | ssh keys - id_rsa
    become: yes
    become_user: "{{ build_user }}"
    command: cp {{build_user_home}}/{{ base_ssh_dir }}/id_rsa {{build_user_home}}/.ssh/id_rsa
    ignore_errors: yes

  - name: setup_user | ssh keys - id_rsa.pub
    become: yes
    become_user: "{{ build_user }}"
    command: cp {{build_user_home}}/{{ base_ssh_dir }}/id_rsa.pub {{build_user_home}}/.ssh/id_rsa.pub
    ignore_errors: yes

  - name: setup_user | ssh keys - id_dsa
    become: yes
    become_user: "{{ build_user }}"
    command: cp {{build_user_home}}/{{ base_ssh_dir }}/id_dsa {{build_user_home}}/.ssh/id_dsa
    ignore_errors: yes

  - name: setup_user | ssh keys - id_dsa.pub
    become: yes
    become_user: "{{ build_user }}"
    command: cp {{build_user_home}}/{{ base_ssh_dir }}/id_dsa.pub {{build_user_home}}/.ssh/id_dsa.pub
    ignore_errors: yes

  - name: setup_user | ssh keys - authorized_keys
    become: yes
    become_user: "{{ build_user }}"
    ignore_errors: yes
    command: cp {{build_user_home}}/{{ base_ssh_dir }}/authorized_keys {{build_user_home}}/.ssh/authorized_keys
             removes={{build_user_home}}/{{ base_ssh_dir }}/

  - name: setup_user | ssh keys - file attributes for authorized keys
    become: yes
    become_user: "{{ build_user }}"
    ignore_errors: yes
    file: path={{build_user_home}}/.ssh/{{item.name}} mode={{item.attr}} state=file
    with_items:
     - {name: id_rsa, attr: 600}
     - {name: id_rsa.pub,  attr: 644}
     - {name: id_dsa, attr: 600}
     - {name: id_dsa.pub,  attr: 644}
     - {name: authorized_keys, attr: 600}
