---
  - name: setup_user | install sudo for debian
    apt: pkg=sudo update_cache=yes state=latest force=yes
    when: ansible_distribution == 'Debian'

  - name: setup_user | install sudo for suse
    zypper: name=sudo state=present
    when: ansible_distribution == 'Suse' or ansible_distribution == 'SLES'

  - name: setup_user | Add group
    become: yes
    become_user: root
    group: name="{{item}}" state=present
    with_items:
      - "{{build_group}}"

  - name: setup_user | create {{build_user_home}} base dir
    become: yes
    become_user: root
    file: path="{{home_base_dir}}" state=directory 

  - name: setup_user | Add user
    become: yes
    become_user: root
    user: name="{{ build_user }}" home={{build_user_home}} uid="{{ build_user_uid }}"
      group={{build_group}} shell="/bin/bash"
