---
  - name: Install compiler, etc.
    tags:  install_compilers
    sudo: yes
    apt:  name={{item}}
    with_items:
      - gcc
      - make
      - openssl
      - build-essential
      - zlib1g-dev
      - libreadline-dev
      - libssl-dev
      - libcurl4-openssl-dev
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: install repos first
    tags: install_checkscripts
    sudo: yes
    copy: src=centos/sensu.repo dest=/etc/yum.repos.d/sensu.repo mode=0644
    when: ansible_os_family == 'RedHat'
  - stat: path=/usr/local/bin/ruby
    register: rubyst
  - name: install Ruby 2.0 (wget)
    tags: install_checkscripts
    sudo: yes
    command:  wget ftp://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p598.tar.gz chdir=/opt
    when: not rubyst.stat.exists
  - name: install Ruby 2.0 (tar)
    tags: install_checkscripts
    sudo: yes
    command:  tar xvzf  ruby-2.0.0-p598.tar.gz chdir=/opt
    when: not  rubyst.stat.exists
  - name: install Ruby 2.0 (configure)
    tags: install_checkscripts
    sudo: yes
    command:  ./configure chdir=/opt/ruby-2.0.0-p598
    when: not  rubyst.stat.exists
  - name: install Ruby 2.0 (make)
    tags: install_checkscripts
    sudo: yes
    command:  make chdir=/opt/ruby-2.0.0-p598
    when: not  rubyst.stat.exists
  - name: install Ruby 2.0 (make install)
    tags: install_checkscripts
    sudo: yes
    command:  make install chdir=/opt/ruby-2.0.0-p598
    when: not  rubyst.stat.exists
  - name: make sensu conf.d dir
    tags: install_checkscripts
    sudo: yes
    file: path=/etc/sensu/conf.d state=directory
  - name: Install sensu-repo signing key.
    sudo: yes
    apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg   state=present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Install sensu-repo repository entry.
    sudo: yes
    apt_repository: repo='deb  http://repos.sensuapp.org/apt sensu main' state=present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Install sensu itself
    sudo: yes
    apt:  name=sensu
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Install sensu itself
    sudo: yes
    command: /usr/local/bin/gem install sensu sensu-em
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11'
  - name: Install sensu itself
    sudo: yes
    shell:  yum install -y sensu
    when: ansible_os_family == 'RedHat'
  - name: Copy in Sensu Rabbitmq configs
    sudo: yes
    tags: rabbitmq
    template:  src=conf.d/{{item}}.j2   dest=/etc/sensu/conf.d/{{item}}
    with_items:
      - rabbitmq.json
      - client.json
  - name: Copy in Notice-Change scripts
    sudo: yes
    tags: copyinitscripts
    copy:  src=restart-upon-change.sh     dest=/etc/sensu/restart-upon-change.sh   mode=0755
  - name: Make SSL certificate work for now, to keep clean.
    sudo: yes
    tags: ssl_certs
    file: path=/etc/sensu/ssl state=directory
  - name: Copy in Sensu SSL certificates to /etc/sensu/ssl also.
    sudo: yes
    tags: ssl_certs
    copy:  src=ssl_certs/client/{{item}}   dest=/etc/sensu/ssl/{{item}}
    with_items:
      - cert.pem
      - key.pem
  - name: install sensu plug-in for Ruby2.0
    sudo: yes
    tags: install_checkscripts
    shell: /usr/local/bin/gem install sensu-plugin
  - name: make sure plugins-dir is there.
    tags: install_checkscripts
    sudo: yes
    file: path=/etc/sensu/plugins/system  state=directory
  - name: copy in scripts for sensu master.
    sudo: yes
    tags: install_checkscripts
    copy:  src=plug-ins/{{item}}   dest=/etc/sensu/plugins/{{item}}  mode=0755
    with_items:
      - check-procs.rb
      - system/check-disk.rb
      - system/disk-usage-metrics.rb
  - name: configure services
    sudo: yes
    tags: sensu_services
    shell:  update-rc.d "{{item}}" defaults
    with_items:
      - sensu-client
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Run Sensu client Code in cron reboot
    cron: name="Run Sensu client Code"
          job="/usr/local/bin/sensu-client -d /etc/sensu/conf.d -b -l /var/log/sensu/sensy-client.log" 
          special_time=reboot user=root state=absent
    tags: copyinitscripts
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11'


  - name: Copy in Sensu init.d files
    sudo: yes
    tags: copyinitscripts
    copy:  src=init.d/{{item}}   dest=/etc/init.d/{{item}}  mode=0755
    with_items:
      - sensu-api
      - sensu-client
      - sensu-server
      - sensu-service
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11'
  - name: Copy in Sensu init.d files
    sudo: yes
    tags: copyinitscripts
    file:  state=link   src=/etc/init.d/{{item}}   dest=/etc/init.d/rc3.d/S90{{item}}  mode=0755
    with_items:
      - sensu-client
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11'
  - name: Add user if necessary
    sudo: yes
    tags: copyinitscripts
    user:  name=sensu
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11'
  - name: Make run-dir writeable as necessary.
    sudo: yes
    tags: copyinitscripts
    file: path={{item}}  owner=sensu mode=0755  state=directory
    with_items:
      - /var/run/sensu
      - /var/log/sensu
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11'
  - name: Make log-file writeable as necessary
    sudo: yes
    tags: copyinitscripts
    file: path=/var/log/sensu/sensu-client.log  owner=sensu mode=0644  state=absent
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11'

  - name: configure services
    sudo: yes
    tags: sensu_services
    shell:  chkconfig "{{item}}"  on
    with_items:
      - sensu-client
    when: ansible_os_family == 'RedHat'
  - name: make sure services are stopped before starting.
    sudo: yes
    tags: sensu_services
    service:  name="{{item}}" state=stopped
    with_items:
      - sensu-client
    # when: not (ansible_distribution == 'Suse')
  - name: start services
    sudo: yes
    tags: sensu_services
    service:  name="{{item}}" state=started
    with_items:
      - sensu-client
    # when: not (ansible_distribution == 'Suse')

  - name: Run Sensu check-for-restart every so often.
    cron: name="Run Sensu restart-client Code"
          job="sh /etc/sensu/restart-upon-change.sh " 
          minute="*/20" user=root state=present
    tags: copyinitscripts
    when: ansible_distribution == 'Suse' and ansible_distribution_major_version == '11'
