---
  - name: cleanup | check if .npm exists
    stat:
      path: "{{ build_user_home }}/.npm"
    register: stat_result
    tags: npm_cleanup

  - name: cleanup | rm .npm
    become: yes
    become_user: "{{ build_user }}"
    file: path="{{ build_user_home }}/.npm" state=absent
    when: stat_result.stat.exists == True
    tags: npm_cleanup
