---
  - name: prepare_env | create all the tools folders
    become: yes
    become_user: "{{ build_user }}"
    file: path={{item}} state=directory owner="{{ build_user }}"
    with_items:
      - "{{tools_home}}/ant"
      - "{{tools_home}}/maven"
      - "{{tools_home}}/jdk64_31"
      - "{{tools_home}}/jdk7"
      - "{{tools_home}}/jdk8"
      - "{{tools_home}}/jdk10"
      - "{{tools_home}}/forrest"
      - "{{build_user_home}}/.m2/"
      - "{{build_user_home}}/.gradle/"
      - "{{tools_home}}/gradle"
      - "{{build_user_home}}/.ssh/"

  - name: prepare_env | create all the tools folders
    become: yes
    become_user: "{{ build_user }}"
    when: project == "re"
    file: path={{item}} state=directory owner="{{ build_user }}"
    with_items:
      - "{{build_user_home}}/profiles/"
      - "{{build_user_home}}/profiles/jenkins/"
      - "{{build_user_home}}/profiles/devci/"


  - name: prepare_env | install tools necessary for ansible exec - centos
    become: yes
    become_user: root
    yum: name={{item}} state=present
    with_items:
    - zip
    - unzip
    - yum-utils
    when: ansible_os_family == "RedHat"
