---
- name: check if build_user is set
  fail: msg='Bailing out. this play requires username, Please pass in the form  -e \"build_user=xyz\"'
  when: build_user is not defined

- include: setup_user.yml

- include: npm_cleanup.yml

- include_vars: "{{ secret_profile_file }}"

- include: setup_user_sshkeys.yml
  when: ssh_url is defined

- include: readonly_sshkeys.yml
  when: readonly_ssh is defined

- include: prepare_env.yml

- include: install_jdk10.yml

- include: install_jdk8.yml

- include: install_jdk8_171.yml

- include: install_gradle.yml

- include: install_maven.yml
  tags: install_maven

- include: install_ant.yml
  tags: install_ant

- include: install_sonar_ant_task.yml
  tags: sonar_ant_task

- include: install_tools.yml
  tags: install_tools

- include: setup_user_configs.yml
  when: project != 'dev' and build_user != "nobody"

- include: update_configs.yml
  when: build_user != "nobody"

- include: re_readonly_update_configs.yml

- include: mvn-gpg-nexus-password.yml
  when: project != 'dev'

- include: download_m2.yml
