---
  - name: cleaning task for yum
    command: /usr/bin/yum clean all
    become: yes
    become_user: root
    when: ansible_os_family == "RedHat"

  - name: delete cache files
    file: path=/var/cache/yum state=absent
    become: yes
    become_user: root
    when: ansible_os_family == "RedHat"
