---
  - set_fact: ssh_url="{{ readonly_ssh_url }}"
    when: project == "re" and build_user == "nobody"

  - set_fact: base_ssh_url="{{ ssh_url | basename }}"
  - set_fact: base_ssh_dir="{{ base_ssh_url.split('.')[0] }}"

  - name: setup_user | ssh keys - Download
    become: yes
    become_user: "{{ build_user }}"
    when: project != 'dev'
    get_url: url={{ ssh_url }} dest={{build_user_home}}/{{ base_ssh_url }} force=yes timeout=120
             url_password={{ url_download_key }} url_username=releng

  - name: setup_user | ssh keys - Download
    become: yes
    become_user: "{{ build_user }}"
    when: project == 'dev'
    copy: src={{ ssh_url }} dest={{build_user_home}}/{{ base_ssh_url }} owner={{ build_user }}  group={{ build_group }} mode=0644

  - name: setup_user | ssh keys - untar
    become: yes
    become_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ base_ssh_url }} dest={{build_user_home}}/

  - name: setup_user | delete ssh keys tarball
    become: yes
    become_user: "{{ build_user }}"
    file: path={{build_user_home}}/{{ base_ssh_url }} state=absent

  - name: setup_user | create ssh directory
    become: yes
    become_user: "{{ build_user }}"
    file: path={{build_user_home}}/.ssh owner={{ build_user }} group={{ build_group }} state=directory mode=700

  - name: setup_user | check id_rsa file exists
    stat:
      path: "{{ build_user_home }}/{{ base_ssh_dir }}/id_rsa"
    register: id_rsa_stat_result

  - name: setup_user | ssh keys - id_rsa
    become: yes
    become_user: "{{ build_user }}"
    copy: src="{{ build_user_home }}/{{ base_ssh_dir }}/id_rsa" dest="{{ build_user_home }}/.ssh/id_rsa" owner="{{ build_user }}" group="{{ build_group }}" mode=0600 remote_src=true
    when: id_rsa_stat_result.stat.exists == true

  - name: setup_user | check id_rsa.pub file exists
    stat:
      path: "{{ build_user_home }}/{{ base_ssh_dir }}/id_rsa.pub"
    register: id_rsa_pub_stat_result

  - name: setup_user | ssh keys - id_rsa.pub
    become: yes
    become_user: "{{ build_user }}"
    copy: src="{{ build_user_home }}/{{ base_ssh_dir }}/id_rsa.pub" dest="{{ build_user_home }}/.ssh/id_rsa.pub" owner="{{ build_user }}" group="{{ build_group }}" mode=0644 remote_src=true
    when: id_rsa_pub_stat_result.stat.exists == true

  - name: setup_user | check id_dsa file exists
    stat:
      path: "{{ build_user_home }}/{{ base_ssh_dir }}/id_dsa"
    register: id_dsa_stat_result

  - name: setup_user | ssh keys - id_dsa
    become: yes
    become_user: "{{ build_user }}"
    copy: src="{{ build_user_home }}/{{ base_ssh_dir }}/id_dsa" dest="{{ build_user_home }}/.ssh/id_dsa" owner="{{ build_user }}" group="{{ build_group }}" mode=0600 remote_src=true
    when: id_dsa_stat_result.stat.exists == true

  - name: setup_user | check id_dsa.pub file exists
    stat:
      path: "{{ build_user_home }}/{{ base_ssh_dir }}/id_dsa.pub"
    register: id_dsa_pub_stat_result

  - name: setup_user | ssh keys - id_dsa.pub
    become: yes
    become_user: "{{ build_user }}"
    copy: src="{{ build_user_home}}/{{ base_ssh_dir }}/id_dsa.pub" dest="{{ build_user_home }}/.ssh/id_dsa.pub" owner="{{ build_user }}" group="{{ build_group }}" mode=0644 remote_src=true
    when: id_dsa_pub_stat_result.stat.exists == true

  - name: setup_user | check if "{{ build_user_home }}/{{ base_ssh_dir }}/authorized_keys" exists
    stat:
      path: "{{ build_user_home }}/{{ base_ssh_dir }}/authorized_keys"
    register: ssh_auth_keys_stat_result

  - name: setup_user | ssh keys - authorized_keys
    become: yes
    become_user: "{{ build_user }}"
    ignore_errors: yes
    copy: src="{{ build_user_home }}/{{ base_ssh_dir }}/authorized_keys" dest="{{ build_user_home }}/.ssh/authorized_keys" owner="{{ build_user }}" group="{{ build_group }}" mode=0600 remote_src=true
    when: ssh_auth_keys_stat_result.stat.exists == true

  - name: setup_user | check if "{{ build_user_home }}/{{ base_ssh_dir }}/config" exists
    stat:
      path: "{{ build_user_home }}/{{ base_ssh_dir }}/config"
    register: ssh_config_stat_result

  - name: setup_user | ssh keys - config
    become: yes
    become_user: "{{ build_user }}"
    ignore_errors: yes
    copy: src="{{ build_user_home }}/{{ base_ssh_dir }}/config" dest="{{ build_user_home }}/.ssh/config" owner="{{ build_user }}" group="{{ build_group }}" mode=0644 remote_src=true
    when: ssh_config_stat_result.stat.exists == true

  - name: setup_user | root | autorized_keys
    become: yes
    become_user: root
    file: path=/root/.ssh state=directory

  - name: setup_user | root | autorized_keys
    become: yes
    become_user: root
    copy: src="authorized_keys" dest="/root/.ssh/authorized_keys" force=yes 
    when: ansible_virtualization_type == "docker"

  - name: setup_user | add lines at EOF /etc/ssh/sshd_config
    become: yes
    become_user: root
    lineinfile: dest="/etc/ssh/sshd_config" line="{{item}}" insertafter=EOF
    with_items:
     - "PasswordAuthentication no"
     - "PermitRootLogin without-password"
     - "PubkeyAuthentication yes"
    when: ansible_virtualization_type == "docker"

  - name: setup_user | disable PermitRootLogin
    become: yes
    become_user: root
    lineinfile: dest="/etc/ssh/sshd_config" regexp="PermitRootLogin yes" line="#PermitRootLogin yes"
    when: ansible_virtualization_type == "docker"
