---
 - name: Install MySQL only for RedHat flavours
   include_vars: mysql.yml
   when: ((ansible_os_family == "CentOS" or ansible_os_family == "RedHat") and  ansible_distribution_major_version == "6")
   
 - include: install_mysql.yml
   when: ((ansible_os_family == "CentOS" or ansible_os_family == "RedHat") and  ansible_distribution_major_version == "6")
   
 - include: secure_installation.yml
   when: ((ansible_os_family == "CentOS" or ansible_os_family == "RedHat") and  ansible_distribution_major_version == "6")
