- name: Install_Libraries | Install Debian Libraries and build Tools
  sudo: yes
  sudo_user: root
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
    - debian-keyring
    - debian-archive-keyring
  tags: install_libraries

- name: Install_Libraries | Install Debian Libraries and build Tools
  sudo: yes
  sudo_user: root
  apt: pkg={{item}} update_cache=yes state=latest
  tags: install_libraries
  with_items:
      - ant
      - asciidoc
      - autoconf
      - automake
      - bison
      - build-essential
      - cabal-install
      - clamav
      - cmake
      - curl
      - dh-make
      - dpkg-dev
      - debhelper
      - devscripts
      - erlang-base
      - erlang-eunit
      - erlang-dev
      - expect
      - flex
      - g++
      - g++-multilib
      - gcc
      - gcc-multilib
      - ghc
      - git
      - git-core
      - libxml2-dev
      - libxslt1-dev
      - libsqlite3-dev
      - libldap2-dev
      - libmysqlclient-dev
      - libkrb5-dev
      - asciidoc
      - libzip-dev
      - libfuse-dev
      - libcppunit-dev
      - lib32z1
      - lib32ncurses5
      - lib32bz2-1.0
      - libbit-vector-perl
      - libboost-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libc6-dev-i386
      - libclass-accessor-class-perl
      - libcppunit-dev
      - libcurl4-openssl-dev
      - libevent-dev
      - libfuse-dev
      - libglib2.0-dev
      - libjpeg8-dev
      - liblzo2-dev
      - libmono-system-web2.0-cil
      - libqt4-dev
      - libsasl2-dev
      - libssl-dev
      - libtool
      - libxml-xpath-perl
      - libz-dev
      - make
      - mingw32
      - mingw32-binutils
      - mingw32-runtime
      - mono-devel
      - mono-gmcs
      - php5
      - php5-cli
      - php5-dev
      - php-pear
      - pkg-config
      - protobuf-compiler
      - python-all
      - python-all-dev
      - python-all-dbg
      - python-boto
      - python-dev
      - python-setuptools
      - python-support
      - re2c
      - reprepro
      - ruby
      - ruby-dev
      - sharutils
      - texlive-latex-base
      - xmlto
