---
 - name: get data directory
   shell: /usr/bin/my_print_defaults "{{ __mysql_daemon }}" | sed -n "s/^--datadir=//p" | tail -n 1
   register: result

 - name: "enable mysql for first time"
   service:
     name: "{{ __mysql_daemon }}"
     enabled: yes
   when: (installed_mysql_packages | bool)

 # Starting mysql first time to create valid database
 - name: "start mysql first time"
   service:
     name: "{{ __mysql_daemon }}"
     state: started
   when: (installed_mysql_packages | bool)

 - name: stop mysql
   service:
     name: "{{ __mysql_daemon }}"
     state: stopped
   when: (installed_mysql_packages | bool)

 - name: "Create {{ cinder_disk_partition }} directory"
   file:
     path: "{{ cinder_disk_partition }}"
     owner: root
     group: root
     mode: 0755
     state: directory
     recurse: yes
   when: (installed_mysql_packages | bool)

 - name: copy data directory
   shell: "cp -par /var/lib/mysql {{ cinder_disk_partition }}"
   when: (installed_mysql_packages | bool)

 - name: update mysql configuration
   template:
     src: my.cnf.j2
     dest: /etc/my.cnf
     owner: root
     group: root
     mode: 0644
   notify: restart mysql

 - name: add context mapping
   shell: semanage fcontext -a -t mysqld_db_t "{{ mysql_datadir }}(/.*)?"
   when: (installed_mysql_packages | bool)

 - name: apply context mapping to running system
   shell: "restorecon -R -v {{ cinder_disk_partition }}/mysql"
   when: (installed_mysql_packages | bool)

 - name: start mysql first time after changing data directory
   service:
     name: "{{ __mysql_daemon }}"
     state: started
   when: (installed_mysql_packages | bool)

 - name: Disallow root login remotely
   command: 'mysql -NBe "{{ item }}"'
   with_items:
     - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('"{{ mysql_host }}"', '127.0.0.1', '::1')
   when: (installed_mysql_packages | bool)

 - name: Get list of hosts for the root user.
   command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="{{ mysql_host }}") ASC'
   register: mysql_root_hosts
   when: (installed_mysql_packages | bool)

 # Set root password for MySQL < 5.7.x.
 - name: "Update MySQL root password for {{ mysql_host }} root account (< 5.7.x)."
   shell: >
     mysql -u root -NBe
     'SET PASSWORD FOR "{{ mysql_root_username }}"@"{{ item }}" = PASSWORD("{{ mysql_root_password }}");'
   with_items: "{{ mysql_root_hosts.stdout_lines }}"
   when: (installed_mysql_packages | bool)

 # Has to be after the root password assignment, for idempotency.
 - name: Copy .my.cnf file with root password credentials.
   template:
     src: "user-my.cnf.j2"
     dest: "{{ mysql_user_home }}/.my.cnf"
     owner: root
     group: root
     mode: 0600
   when: (installed_mysql_packages | bool)

 - name: Get list of hosts for the anonymous user.
   command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
   register: mysql_anonymous_hosts
   when: (installed_mysql_packages | bool)

 - name: Remove anonymous MySQL users.
   shell: >
     mysql -u root -NBe 'DROP USER ""@"{{ item }}";'
   with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"
   when: (installed_mysql_packages | bool)

 - name: Remove MySQL test database.
   shell: >
     mysql -u root -NBe 'DROP DATABASE test;'
   when: (installed_mysql_packages | bool)
