---
  - name: install_libraries | zypper in
    sudo: yes
    zypper: pkg={{item}} disable_gpg_check=yes state=latest 
    with_items:
      - http://ftp.twaren.net/Linux/OpenSuSE/repositories/M17N/SLE_11_SP3/x86_64/googletest-1.7.0-16.1.x86_64.rpm
      - http://ftp.twaren.net/Linux/OpenSuSE/repositories/M17N/SLE_11_SP3/x86_64/googletest-devel-1.7.0-16.1.x86_64.rpm

  - name: install_libraries | zypper in
    sudo: yes
    zypper: pkg={{item}} disable_gpg_check=yes state=latest 
    with_items:
      - gd-devel
      - libpng-devel
      - libjpeg-devel
      - cairo-devel
      - freetype2-devel
      - glib2-devel
      - intltool
      - libart_lgpl-devel
      - pango-devel
      - gettext-tools
      - ruby-devel
      - lua-devel
      - tcpd-devel
      - dejagnu
      - googletest-devel
      - rsh 
      - apache2-devel
      - x11-devel
      - pcre-devel  
      - libapr-util1-devel 
      - xorg-x11-devel 
      - fdupes 
      - tcl-devel 
      - libconfuse-devel 
      - rrdtool-devel 

