- hosts: master
  vars:
    build_user_uid: 1001
    slave: False
    jenkins_http_port: 8000
    build_user_home: /var/lib/jenkins
    build_user: jenkins
    build_group: users
    jenkins_configuration: /etc/default/jenkins
    jenkins_run_standalone: yes
    jenkins_name: jenkins
    jenkins_java: /usr/bin/java
    jenkins_pidfile: /var/run/jenkins.pid
    jenkins_logdir: /var/log/jenkins
    jenkins_log: "{{jenkins_logdir}}/{{jenkins_name}}.log"
    jenkins_prefix: "/"
    jenkins_war: /usr/share/jenkins/jenkins.war
    jenkins_plugins: true
    gpg_file: ~/password_gpg.txt
    nexus_file: ~/password_gpg.txt
    security_file: ~/password_gpg.txt
    push_password: false

  roles:
    - common
    - jenkins-master
