---
 - hosts: default
   gather_facts: yes
   vars:
     cinder_disk_partition: "/grid/1"
     mysql_host: "localhost"
     tomcat_url: "http://dev.hortonworks.com.s3.amazonaws.com/ARTIFACTS/apache-tomcat-7.0.69.tar.gz"
     s3_fortify_url: "http://dev.hortonworks.com.s3.amazonaws.com/Fortify"
     ssc_server_zip: "HPE_Security_Fortify_SSC_Server_16.10.zip"
     ssc_war_zip: "HPE_Security_Fortify_SSC_16.10_Server_WAR.zip"
     fortify_install_temp: "/tmp/fortify"
     mysql_jdbc_driver: "mysql-connector-java-5.1.38-bin.jar"
     s3_dev_bucket: "dev.hortonworks.com"
     jdk8_url: "http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/jdk-8u91-linux-x64.tar.gz"
     jdk8_version: "1.8.0_91"
     jdk8_home: "/grid/1/jdk8"
     jdk8_tar: "jdk-8u91-linux-x64.tar.gz"
   roles:
    - fortify
