#!/bin/sh

### BEGIN INIT INFO
# Provides:		massageHostname
# Required-Start:	
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Massage hostname to FQDN
### END INIT INFO

set -e

host=`hostname`

case "$host" in
	*.*)	echo "Nothing to do, hostname is $host"
		;;
	*)	echo Setting hostname to ${host}.ec2.internal
		hostname ${host}.ec2.internal
		;;
esac
