   - name: slave setup | install libs
     apt: name={{item}} state=latest
     tags: install_libraries
     with_items:
       - libselinux-python
       - java-1.7.0-openjdk
       - wget
       - gcc
       - curl
       - curl-devel
       - openssl-devel
       - expat-devel
       - python-setuptools
       - python-dev
       - pdsh
       - perl
       - perl-URI
       - git
       - openssh-server
       - zlib-devel
       - bzip2-devel
       - ncurses-devel
