FROM 

RUN zypper rr ARTIFACTS && zypper ar http://sles-repos-re.eng.hortonworks.com/TD-repo/ hosted_sp1
RUN zypper refresh && zypper install -y wget yaml

RUN pip install ansible=2.9.0
COPY . /root/ansible/
ENV ANSIBLE_CONFIG=/root/ansible/ansible/config/ansible.cfg
RUN ansible-playbook /root/ansible/ansible/playbooks/setup-images/setup_sles11sp1.yml  -e "username=jenkins project_name=re" -i /root/ansible/ansible/config/docker_hosts --vault-password-file=/root/ansible/re_vault_pass.txt --connection=local

