---
  - name: "Setup Tools Dir"
    sudo: yes
    sudo_user: jenkins
    file: path={{item}} state=directory owner=jenkins
    with_items:
      - "{{tools_home}}"
      - "{{tools_home}}/ant"
      - "{{tools_home}}/maven"
      - "{{tools_home}}/jdk64_31"
      - "{{tools_home}}/jdk7"
      - "{{tools_home}}/forrest"
      - /home/jenkins/.m2/
      - /home/jenkins/.ssh/

  - name: "Download Maven"
    sudo: yes
    sudo_user: jenkins
    get_url: url={{maven_url}} dest={{tools_home}}/maven/maven.tar.gz mode=0744

  - name: "Download Ant"
    sudo: yes
    sudo_user: jenkins
    get_url: url={{ant_url}} dest={{tools_home}}/ant/ant.tar.gz mode=0744

  - name: "Download Forrest"
    sudo: yes
    sudo_user: jenkins
    get_url: url={{forrest_url}} dest={{forrest_home}}/forrest.tar.gz mode=744

  - name: "Untar Maven"
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{tools_home}}/maven/maven.tar.gz dest={{tools_home}}/maven

  - name: "Untar Ant"
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{tools_home}}/ant/ant.tar.gz dest={{tools_home}}/ant

  - name: "Untar Forrest"
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{forrest_home}}/forrest.tar.gz dest={{tools_home}}/forrest

  - name: "symlink Maven -> latest"
    sudo: yes
    sudo_user: jenkins
    file: src=apache-maven-{{ mvn_version }} dest={{tools_home}}/maven/latest state=link

  - name: "symlink Ant -> latest"
    sudo: yes
    sudo_user: jenkins
    file: src=apache-ant-1.9.4 dest={{tools_home}}/ant/latest state=link

  - name: "symlink Forrest -> latest"
    sudo: yes
    sudo_user: jenkins
    file: src=apache-forrest-{{forrest_version}} dest={{forrest_home}}/latest state=link

  - name: "cleanup archives"
    sudo: yes
    sudo_user: jenkins
    file: path={{tools_home}}/{{item}} state=absent
    with_items:
      - ant/ant.tar.gz
      - maven/maven.tar.gz
      - forrest/forrest.tar.gz
      - "{{tools_home}}/jdk64_31/jdk6.tar.gz"
      - "{{tools_home}}/jdk7/jdk7.gz"
      - "{{ ssh_url_dest }}"
      - "{{ gpgkey_dest }}"
      - "{{ gpgkey_dest }}.tar.gz"
