---
  - name: install_ant | Download Ant
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ant_url}} dest={{tools_home}}/ant/ant.tar.gz mode=0744

  - name: install_ant | Untar Ant
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{tools_home}}/ant/ant.tar.gz dest={{tools_home}}/ant

  - name: install_ant | Download Ant {{ant_old_version}}
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ant_old_url}} dest={{tools_home}}/ant/ant_old.tar.gz mode=0744

  - name: install_ant | Untar Ant {{ant_old_version}}
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{tools_home}}/ant/ant_old.tar.gz dest={{tools_home}}/ant

  - name: install_ant | Download ant-contrib-1.0b2.jar file
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ant_contrib_url}} dest={{tools_home}}/ant/apache-ant-{{ant_old_version}}/lib/ant-contrib-1.0b2.jar mode=0744

  - name: install_ant | symlink Ant -> latest
    sudo: yes
    sudo_user: "{{ build_user }}"
    file: src=apache-ant-1.9.4 dest={{tools_home}}/ant/latest state=link
