---
  - name: "Download Jdk6" 
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{jdk6_url}} dest={{jdk6_home}}/{{ jdk6_url | basename }} mode=744
    tags:
      - install_jdk
      - install_jdk6

  - name: "Download Jdk7" 
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{jdk7_url}} dest={{jdk7_home}}/{{ jdk7_url | basename }} mode=744
    tags:
      - install_jdk
      - install_jdk7

  - name: "Install Jdk7"
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{jdk7_home}}/{{ jdk7_url | basename }} dest={{jdk7_home}}
    tags:
      - install_jdk
      - install_jdk7

  - name: "Symlink jdk7 -> latest"
    sudo: yes
    sudo_user: "{{ build_user }}"
    file: src=jdk1.7.0_21 dest={{jdk7_home}}/latest state=link 
    tags:
      - install_jdk
      - install_jdk7
    
  - name: "Install Jdk6"
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{jdk6_home}}/{{ jdk6_url | basename }} dest={{jdk6_home}}
    tags:
      - install_jdk
      - install_jdk6

  - name: "Symlink jdk6 -> latest"
    sudo: yes
    sudo_user: "{{ build_user }}"
    file: src=jdk1.6.0_31 dest={{jdk6_home}}/latest state=link 
    tags:
      - install_jdk
      - install_jdk6

  - name: Install JCE Policy files for JDK7 | Download tar
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url="http://s3.amazonaws.com/dev.hortonworks.com/RLENG/UnlimitedJCEPolicyJDK7.zip" dest={{jdk7_home}}/UnlimitedJCEPolicyJDK7.zip mode=744
    tags:
      - install_jdk
      - install_jdk7

  - name: "unzip JCE Policy files"
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{jdk7_home}}/UnlimitedJCEPolicyJDK7.zip dest={{jdk7_home}}
    tags:
      - install_jdk
      - install_jdk7

  - name: Create lib/security for jdk7
    sudo: yes
    sudo_user: "{{ build_user }}"
    file: path={{ jdk7_home }}/jdk1.7.0_21/lib/security state=directory
    tags:
      - install_jdk
      - install_jdk7

  - name: "Install Jdk7"
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{jdk7_home}}/UnlimitedJCEPolicyJDK7.zip dest={{jdk7_home}}/
    tags:
      - install_jdk
      - install_jdk7

  - name: "copy JCE Policy files for JDK7"
    sudo: yes
    sudo_user: "{{ build_user }}"
    shell: cp -r {{jdk7_home}}/UnlimitedJCEPolicy/*.jar {{jdk7_home}}/jdk1.7.0_21/lib/security/
    tags:
      - install_jdk
      - install_jdk7
   
