---
  - name: install_tools | Download gradle
    sudo: yes
    sudo_user: jenkins
    tags: install_gradle
    get_url: url=https://services.gradle.org/distributions/gradle-1.6-all.zip dest={{tools_home}}/gradle/gradle.zip mode=0744 force=yes

  - name: install_tools | Download Maven
    sudo: yes
    sudo_user: jenkins
    get_url: url={{maven_url}} dest={{tools_home}}/maven/maven.tar.gz mode=0744

  - name: install_tools | Download Ant
    sudo: yes
    sudo_user: jenkins
    get_url: url={{ant_url}} dest={{tools_home}}/ant/ant.tar.gz mode=0744

  - name: install_tools | Download Forrest
    sudo: yes
    sudo_user: jenkins
    get_url: url={{forrest_url}} dest={{forrest_home}}/forrest.tar.gz mode=744

  - name: install_tools | Untar gradle
    sudo: yes
    sudo_user: jenkins
    tags: install_gradle
    unarchive: copy=no src={{tools_home}}/gradle/gradle.zip dest={{tools_home}}/gradle

  - name: install_tools | Untar Maven
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{tools_home}}/maven/maven.tar.gz dest={{tools_home}}/maven

  - name: install_tools | Untar Ant
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{tools_home}}/ant/ant.tar.gz dest={{tools_home}}/ant

  - name: install_tools | Untar Forrest
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{forrest_home}}/forrest.tar.gz dest={{tools_home}}/forrest

  - name: install_tools | rm symlink gradle -> latest
    sudo: yes
    sudo_user: jenkins
    file: path={{tools_home}}/gradle/latest state=absent
    tags: install_gradle

  - name: install_tools | symlink gradle -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=gradle-1.6 force=yes dest={{tools_home}}/gradle/latest state=link
    tags: install_gradle

  - name: install_tools | capture gradle version
    sudo: yes
    sudo_user: jenkins
    shell: "JAVA_HOME={{tools_home}}/jdk64_31/latest ; PATH=$PATH:{{tools_home}}/jdk64_31/latest/bin ; {{tools_home}}/gradle/latest/bin/gradle --version"
    tags:
      - install_gradle
      - assert_gradle
    register: cmd_result

  - name: install_tools | assert gradle installation
    tags:
      - install_gradle
      - assert_gradle
    assert:
      that:
        - "'Gradle 1.6' in cmd_result.stdout"

  - name: install_tools | symlink Maven -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-maven-{{ mvn_version }} dest={{tools_home}}/maven/latest state=link

  - name: install_tools | symlink Ant -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-ant-1.9.4 dest={{tools_home}}/ant/latest state=link

  - name: install_tools | symlink Forrest -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-forrest-{{forrest_version}} dest={{forrest_home}}/latest state=link
