---
  - name: install_tools | Download gradle
    sudo: yes
    sudo_user: jenkins
    tags: install_gradle
    get_url: url=http://services.gradle.org/distributions/gradle-2.3-bin.zip
      dest={{tools_home}}/gradle/gradle.zip mode=0744 force=yes

  - name: install_tools | mkdirs for Maven
    tags: install_maven
    file: path={{tools_home}}/maven state=directory mode=0755
    sudo: yes
    sudo_user: jenkins
  - name: install_tools | Download Maven
    sudo: yes
    sudo_user: jenkins
    get_url: url={{maven_url}} dest={{tools_home}}/maven/maven.tar.gz mode=0644

  - name: install_tools | Download Maven for Ambari
    sudo: yes
    tags: install_maven
    sudo_user: jenkins
    get_url: url={{maven_ambari_url}} dest={{tools_home}}/maven/maven.{{mvn_ambari_version}}.tar.gz mode=0644 force=no

  - name: install_tools | Download Ant
    sudo: yes
    sudo_user: jenkins
    get_url: url={{ant_url}} dest={{tools_home}}/ant/ant.tar.gz mode=0744

  - name: install_tools | Download Forrest
    sudo: yes
    sudo_user: jenkins
    get_url: url={{forrest_url}} dest={{forrest_home}}/forrest.tar.gz mode=744

  - name: install_tools | Untar gradle
    sudo: yes
    sudo_user: jenkins
    tags: install_gradle
    unarchive: copy=no src={{tools_home}}/gradle/gradle.zip dest={{tools_home}}/gradle

  - name: install_tools | Untar Maven
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{tools_home}}/maven/maven.tar.gz dest={{tools_home}}/maven

  - name: install_tools | Untar Maven for Ambari
    sudo: yes
    sudo_user: jenkins
    tags: install_maven
    unarchive: copy=no src={{tools_home}}/maven/maven.{{mvn_ambari_version}}.tar.gz dest={{tools_home}}/maven

  - name: install_tools | Untar Ant
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{tools_home}}/ant/ant.tar.gz dest={{tools_home}}/ant

  - name: install_tools | Untar Forrest
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{forrest_home}}/forrest.tar.gz dest={{tools_home}}/forrest

  - name: install_tools | rm symlink gradle -> latest
    sudo: yes
    sudo_user: jenkins
    file: path={{tools_home}}/gradle/latest state=absent
    tags: install_gradle

  - name: install_tools | symlink gradle -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=gradle-2.3 force=yes dest={{tools_home}}/gradle/latest state=link
    tags: install_gradle

  - name: install_tools | capture gradle version
    sudo: yes
    sudo_user: jenkins
    shell: "export JAVA_HOME={{tools_home}}/jdk64_31/latest ; {{tools_home}}/gradle/latest/bin/gradle --version"
    tags:
      - install_gradle
      - assert_gradle
    register: cmd_result

  - name: install_tools | assert gradle installation
    tags:
      - install_gradle
      - assert_gradle
    assert:
      that:
        - "'Gradle 2.3' in cmd_result.stdout"

  - name: install_tools | symlink Maven -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-maven-{{ mvn_version }} dest={{tools_home}}/maven/latest state=link

  - name: install_tools | symlink Ant -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-ant-1.9.4 dest={{tools_home}}/ant/latest state=link

  - name: install_tools | symlink Forrest -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-forrest-{{forrest_version}} dest={{forrest_home}}/latest state=link

  - name: install_tools | Remove .tar.gz artifact from Maven install.
    sudo: yes
    tags: install_maven
    sudo_user: jenkins
    file: path={{tools_home}}/maven/maven.{{mvn_ambari_version}}.tar.gz state=absent
