---

  - name: Configuring Jenkins - ssh keys - file attributes for authorized keys
    sudo: yes
    sudo_user: "{{build_user}}"
    copy: src="{{item.src_name}}" dest="{{build_user_home}}/{{item.dest_name}}"
    when: push_password
    with_items:
     - {src_name: "{{gpg_file}}", dest_name: '.password_gpg.txt' }
     - {src_name: "{{nexus_file}}", dest_name: '.nexus_password.txt' }
     - {src_name: "{{security_file}}", dest_name: '.m2/settings-security.xml' }
