---
  - name: setup_user | install sudo for debian
    apt: pkg=sudo update_cache=yes state=latest force=yes
    when: ansible_distribution == 'Debian'

  - name: setup_user | install sudo for suse
    zypper: name=sudo state=present
    when: ansible_distribution == 'Suse' or ansible_distribution == 'SLES'

  - name: setup_user | Add group
    sudo: yes
    sudo_user: root
    group: name="{{item}}" state=present
    with_items:
      - "{{build_group}}"

  - name: setup_user | create {{builds_home}} base dir
    sudo: yes
    sudo_user: root
    file: path="{{home_base_dir}}" state=directory 

  - name: setup_user | Add user
    sudo: yes
    sudo_user: root
    user: name="{{ build_user }}" home={{builds_home}} uid="{{ build_user_uid }}"
      group={{build_group}} shell="/bin/bash"

  - name: setup_user | ssh keys - Download
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{ ssh_url }} dest={{builds_home}}/hortonworksre.tar.gz

  - name: setup_user | ssh keys - untar
    sudo: yes
    sudo_user: "{{ build_user }}"
    unarchive: copy=no src={{builds_home}}/hortonworksre.tar.gz dest={{builds_home}}/

  - name: setup_user | create ssh directory
    sudo: yes
    sudo_user: "{{ build_user }}"
    file: path={{builds_home}}/.ssh state=directory mode=700
   
  - name: setup_user | ssh keys - id_rsa
    sudo: yes
    sudo_user: "{{ build_user }}"
    command: cp {{builds_home}}/hortonworksre/id_rsa {{builds_home}}/.ssh/id_rsa

  - name: setup_user | ssh keys - id_rsa.pub
    sudo: yes
    sudo_user: "{{ build_user }}"
    command: cp {{builds_home}}/hortonworksre/id_rsa.pub {{builds_home}}/.ssh/id_rsa.pub

  - name: setup_user | ssh keys - authorized_keys
    sudo: yes
    sudo_user: "{{ build_user }}"
    command: cp {{builds_home}}/hortonworksre/authorized_keys {{builds_home}}/.ssh/authorized_keys
             removes={{builds_home}}/hortonworksre/

  - name: setup_user | ssh keys - file attributes for authorized keys
    sudo: yes
    sudo_user: "{{ build_user }}"
    file: path={{builds_home}}/.ssh/{{item.name}} mode={{item.attr}} state=file
    with_items:
     - {name: id_rsa, attr: 600}
     - {name: id_rsa.pub,  attr: 644}
     - {name: authorized_keys, attr: 600}
