---
  - include_vars: "{{ secret_profile_file }}"

  - name: setup_user_configs | Download gpg keys
    become: yes
    become_user: "{{ build_user }}"
    get_url: url={{ gpgkeys_url }} url_password={{ url_download_key }} url_username=releng
            dest={{ build_user_home }}/{{ gpgkeys_url | basename }} timeout=120

  - name: setup_user_configs | Untar gpg keys archive
    become: yes
    become_user: "{{ build_user }}"
    unarchive: copy=no src={{build_user_home}}/{{ gpgkeys_url | basename }}
        dest={{build_user_home}}/

  - name: setup_user_configs | delete gpg keys tarball
    become: yes
    become_user: "{{ build_user }}"
    file: path={{build_user_home}}/{{ gpgkeys_url }} state=absent

  - name: setup_user_configs | delete gpg secret and key
    become: yes
    become_user: "{{ build_user }}"
    shell: "gpg --batch --yes --delete-secret-and-public-key DF52ED4F7A3A5882C0994C66B9733A7A07513CAD"
    ignore_errors: yes

  - name: setup_user_configs | Import gpg pub
    become: yes
    become_user: "{{ build_user }}"
    shell: "gpg --import {{build_user_home}}/jenkins-gpg-keys/jenkins_pub.gpg"
    ignore_errors: yes

  - name: setup_user_configs | Import gpg secret
    become: yes
    become_user: "{{ build_user }}"
    shell: "gpg --allow-secret-key-import --import {{build_user_home}}/jenkins-gpg-keys/jenkins_sec.gpg"
    ignore_errors: yes
