---
  - name: Configuring Jenkins - Add user
    sudo: yes
    sudo_user: root
    user: name="jenkins" uid={{ jenkins_user_uid }} comment="Jenkins Slave" shell="/bin/bash"
    tags:
      master
      slave

  - name: Configuring Jenkins - ssh keys - Download
    sudo: yes
    sudo_user: jenkins
    get_url: url={{ ssh_url }} dest={{jenkins_home}}/hortonworksre.tar.gz
    tags:
      master
      slave

  - name: Configuring Jenkins - ssh keys - untar
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{jenkins_home}}/hortonworksre.tar.gz dest={{jenkins_home}}/
    tags:
      master
      slave

  - name: Configuring Jenkins - ssh keys - copy
    sudo: yes
    sudo_user: jenkins
    command: cp -R {{jenkins_home}}/hortonworksre/ {{jenkins_home}}/.ssh/
             removes={{jenkins_home}}/hortonworksre/
    tags:
      master
      slave

  - name: Configuring Jenkins - ssh keys - file attributes for ssh dir
    sudo: yes
    sudo_user: jenkins
    file: path={{jenkins_home}}/.ssh/ owner=jenkins mode=700
    tags:
      master
      slave

  - name: Configuring Jenkins - ssh keys - file attributes for authorized keys
    sudo: yes
    sudo_user: jenkins
    file: path={{jenkins_home}}/.ssh/authorized_keys mode=644
    tags:
      master
      slave

  - name: "Download gpg keys "
    sudo: yes
    sudo_user: jenkins
    get_url: url={{ gpgkeys_url }}
            dest={{ jenkins_home }}/
    tags:
      slave

  - name: "Setup jenkins user ssh keys"
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{jenkins_home}}/jenkins-gpg-keys.tar.gz
        dest={{jenkins_home}}/
    tags:
      slave

  - name: "Setup jenkins gpg keys"
    sudo: yes
    sudo_user: jenkins
    command: "gpg --import {{jenkins_home}}/jenkins-gpg-keys/jenkins_pub.gpg "
    tags:
      slave

  - name: "Setup jenkins gpg keys"
    sudo: yes
    sudo_user: jenkins
    command: "gpg --allow-secret-key-import {{jenkins_home}}/jenkins-gpg-keys/jenkins_sec.gpg"
    tags:
      slave

  - name: "create ssh dir"
    sudo: yes
    sudo_user: root
    file: path=/root/.ssh state=directory mode=700
    tags:
      slave

  - name: "update authorized_keys"
    sudo: yes
    sudo_user: root
    copy: src=files/gkesavan_id_rsa.pub dest=/root/.ssh/authorized_keys mode=600
    tags:
      slave
