---
  - name: Configuring Jenkins - Add group
    sudo: yes
    sudo_user: root
    group: name={{jenkins_group}} state=present

  - name: Configuring Jenkins - Add user
    sudo: yes
    sudo_user: root
    user: name="jenkins" home={{jenkins_home}} uid={{ jenkins_user_uid }}
      group={{jenkins_group}} comment="Jenkins Slave" shell="/bin/bash"

  - name: Configuring Jenkins - ssh keys - Download
    sudo: yes
    sudo_user: jenkins
    get_url: url={{ ssh_url }} dest={{jenkins_home}}/hortonworksre.tar.gz

  - name: Configuring Jenkins - ssh keys - untar
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{jenkins_home}}/hortonworksre.tar.gz dest={{jenkins_home}}/

  - name: Configuring Jenkins - ssh keys - copy
    sudo: yes
    sudo_user: jenkins
    command: cp -R {{jenkins_home}}/hortonworksre/ {{jenkins_home}}/.ssh/
             removes={{jenkins_home}}/hortonworksre/

  - name: Configuring Jenkins - ssh keys - file attributes for ssh dir
    sudo: yes
    sudo_user: jenkins
    file: path={{jenkins_home}}/.ssh/ owner=jenkins mode=700

  - name: Configuring Jenkins - ssh keys - file attributes for authorized keys
    sudo: yes
    sudo_user: jenkins
    file: path={{jenkins_home}}/.ssh/authorized_keys mode=644

  - name: Setup ssh keys for user - fix .ssh folder attributes
    sudo: yes
    sudo_user: root
    file: path=/root/.ssh state=directory mode=700

  - name: Setup ssh keys for user - fix authorized_keys file attributes
    sudo: yes
    sudo_user: root
    copy: src=gkesavan_id_rsa.pub dest=/root/.ssh/authorized_keys mode=600
