---
  - include_vars: "{{ secret_profile_file }}"

  - name: "Update limits.conf"
    sudo: yes
    sudo_user: root
    copy: src=limits.conf dest=/etc/security/limits.conf

  - name: "Copy env file"
    sudo: yes
    sudo_user: "{{ build_user }}"
    copy: src=jenkins_env.sh dest={{tools_home}}/env.sh mode=755

  - name: "rm s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    shell: rm -rf {{builds_home}}/.s3cfg
    tags: s3cmd_config

  - name: "setup s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{s3cfg_url}} dest={{builds_home}}/.s3cfg mode=744 
    ignore_errors: yes
    tags: s3cmd_config

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{settings_url}} dest={{builds_home}}/.m2/settings.xml mode=744
    ignore_errors: yes
    tags: nexus_settings

