---
  - name: "Update limits.conf"
    sudo: yes
    sudo_user: root
    copy: src=limits.conf dest=/etc/security/limits.conf
    tags:  updatelimits

  - name: "Copy env file"
    sudo: yes
    sudo_user: jenkins
    copy: src=jenkins_env.sh dest={{tools_home}}/env.sh mode=755

  - name: "rm s3cfg"
    sudo: yes
    sudo_user: jenkins
    shell: rm -rf {{jenkins_home}}/.s3cfg

  - name: "setup s3cfg"
    sudo: yes
    sudo_user: jenkins
    get_url: url={{s3cfg_url}} dest={{jenkins_home}}/.s3cfg mode=744 

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: jenkins
    get_url: url={{settings_url}} dest={{jenkins_home}}/.m2/settings.xml mode=744

