---
  - include_vars: "{{ secret_profile_file }}"
    tags: new_nexus_settings

  - name: "Update limits.conf"
    sudo: yes
    sudo_user: root
    copy: src=limits.conf dest=/etc/security/limits.conf

  - name: "Copy env file"
    sudo: yes
    sudo_user: "{{ build_user }}"
    copy: src=jenkins_env.sh dest={{tools_home}}/env.sh mode=755

  - name: "rm s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    shell: rm -rf {{build_user_home}}/.s3cfg
    tags: s3cmd_config

  - name: "setup s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{s3cfg_url}} dest={{build_user_home}}/.s3cfg mode=744 force=yes timeout=120
    when: project != "re"
    tags: s3cmd_config

  - name: "setup s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{s3cfg_url}} dest={{build_user_home}}/.s3cfg mode=744 force=yes
             timeout=120  url_password={{ url_download_key }} url_username=releng
    when: project == "re"
    tags: s3cmd_config

  - name: "setup s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{s3cfg_url}} dest={{build_user_home}}/profiles/jenkins/.s3cfg mode=744
             force=yes timeout=120  url_password={{ url_download_key }} url_username=releng
    when: project == "re"
    tags: s3cmd_config

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{settings_url}} dest={{build_user_home}}/.m2/settings.xml
             mode=744 force=yes timeout=120
    tags: nexus_settings
    when: project != "re"

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{settings_url}} dest={{build_user_home}}/.m2/settings.xml timeout=120
             mode=744 force=yes url_password={{ url_download_key }} url_username=releng
    tags: nexus_settings
    when: project == "re"

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{settings_url}} dest={{build_user_home}}/.m2/main_settings.xml timeout=120
             mode=744 force=yes url_password={{ url_download_key }} url_username=releng
    tags:
      - nexus_settings
      - new_nexus_settings
    when: project == "re"

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{template_settings_url}} dest={{build_user_home}}/.m2/template_settings.xml timeout=120
             mode=744 force=yes url_password={{ url_download_key }} url_username=releng
    tags:
      - nexus_settings
      - new_nexus_settings
    when: project == "re"

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{settings_url}} dest={{build_user_home}}/profiles/jenkins/settings.xml timeout=120
             mode=744 force=yes url_password={{ url_download_key }} url_username=releng
    when: project == "re"
    tags: nexus_settings

  - name: "setup ./gradle/gradle.properties"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{gradle_properties_url}} dest={{build_user_home}}/.gradle/gradle.properties timeout=120
             mode=744 force=yes url_password={{ url_download_key }} url_username=releng
    tags: gradle_properties
    when: project == "re"

  - name: "setup ./gradle/gradle.properites | update gradle.properties if user is not jenkins"
    shell: sed -i "s;0\/jenkins;0\/{{ build_user }};" "{{ build_user_home }}/.gradle/gradle.properties"
    sudo: yes
    sudo_user: "{{ build_user }}"
    tags: gradle_properties
    when: project == "re" and build_user != "jenkins"

  - name: "setup ./gradle/gradle.properties"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{gradle_properties_url}} dest={{build_user_home}}/.gradle/gradle.properties timeout=120
             mode=744 force=yes
    tags: gradle_properties
    when: project != "re"

  - name: "setup ./gradle/gradle.properties"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{gradle_properties_url}} dest={{build_user_home}}/profiles/jenkins/gradle.properties timeout=120
             mode=744 force=yes url_password={{ url_download_key }} url_username=releng
    when: project == "re"
    tags: gradle_properties
