---
  - include_vars: "{{ secret_profile_file }}"

  - name: "Update limits.conf"
    sudo: yes
    sudo_user: root
    copy: src=limits.conf dest=/etc/security/limits.conf

  - name: "Copy env file"
    sudo: yes
    sudo_user: "{{ build_user }}"
    copy: src=jenkins_env.sh dest={{tools_home}}/env.sh mode=755

  - name: "rm s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    shell: rm -rf {{build_user_home}}/.s3cfg
    tags: s3cmd_config

  - name: "setup s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{s3cfg_url}} dest={{build_user_home}}/.s3cfg mode=744
    when: project != "re"
    tags: s3cmd_config

  - name: "setup s3cfg"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{s3cfg_url}} dest={{build_user_home}}/profiles/jenkins/.s3cfg mode=744
    when: project == "re"
    tags: s3cmd_config

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{settings_url}} dest={{build_user_home}}/.m2/settings.xml 
          mode=744 force=yes
    tags: nexus_settings
    when: project != "re"

  - name: "setup ./m2 settings.xml"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{settings_url}} dest={{build_user_home}}/profiles/jenkins/settings.xml
          mode=744 force=yes
    when: project == "re"
    tags: nexus_settings

  - name: "setup ./gradle/gradle.properties"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{gradle_properties_url}} dest={{build_user_home}}/.gradle/gradle.properties
          mode=744 force=yes
    tags: gradle_properties
    when: project != "re"

  - name: "setup ./gradle/gradle.properties"
    sudo: yes
    sudo_user: "{{ build_user }}"
    get_url: url={{gradle_properties_url}} dest={{build_user_home}}/profiles/jenkins/gradle.properties
          mode=744 force=yes
    when: project == "re"
    tags: gradle_properties
