---
  - name: install_gradle_50 | capture gradle version
    become: yes
    become_user: "{{ build_user }}"
    shell: "export JAVA_HOME={{tools_home}}/jdk8/latest ; {{tools_home}}/gradle/gradle-5.0/bin/gradle --version"
    register: check_gradle
    ignore_errors: yes
    tags: install_gradle_50

  - name: install_gradle_50 | "set fact if gradle version is 5.0"
    set_fact: gradle_exists="true"
    when: check_gradle.rc == 0 and check_gradle.stdout.find('Gradle 5.0') != -1
    tags: install_gradle_50

  - name: install_gradle_50 | skip gradle installation
    debug: msg="skip gradle installation as it is already installed"
    when: gradle_exists is defined
    tags: install_gradle_50

  - name: install_gradle_50 | Download gradle
    become: yes
    become_user: "{{ build_user }}"
    get_url: url=http://dev.hortonworks.com.s3.amazonaws.com/ARTIFACTS/gradle-5.0-bin.zip
      dest={{tools_home}}/gradle/gradle-5.0.zip mode=0744 force=yes timeout=120
    when: gradle_exists is not defined
    tags: install_gradle_50

    # check if "check_gradle" is defined and value is equal to desired gradle version
  - name: install_gradle_50 | Untar gradle
    become: yes
    become_user: "{{ build_user }}"
    unarchive: copy=no src={{tools_home}}/gradle/gradle-5.0.zip dest={{tools_home}}/gradle
    when: gradle_exists is not defined
    tags: install_gradle_50

  - name: install_gradle_50 | capture gradle version
    become: yes
    become_user: "{{ build_user }}"
    shell: "export JAVA_HOME={{tools_home}}/jdk8/latest ; {{tools_home}}/gradle/gradle-5.0/bin/gradle --version"
    register: cmd_result
    tags: install_gradle_50

  - name: install_gradle_50 | assert gradle installation
    assert:
      that:
        - "'Gradle 5.0' in cmd_result.stdout"
    when: gradle_exists is not defined
    tags: install_gradle_50

  - name: install_gradle_50 | delete gradle tarball
    become: yes
    become_user: "{{ build_user }}"
    file: path={{tools_home}}/gradle/gradle-5.0.zip state=absent
    when: gradle_exists is not defined
    tags: install_gradle_50
