---
  - name: install_libraries | uninstall 
    become: yes
    become_user: root
    yum: pkg={{item}} state=absent
    with_items:
      - postgresql-libs
      - rrdtool-1.2.27
      - ruby-libs-1.8.7.352
      - epel-release
    ignore_errors: yes

  - name: centos7_repo_setup | install epel release
    become: yes
    become_user: root
    when: ansible_distribution_major_version|int == 7
    yum: name='http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/epel-release-7-9.noarch.rpm' state=present

  - name: get epel-repo rpm RHEL6
    become: yes
    become_user: root
    shell: yum-config-manager --add-repo https://dl.fedoraproject.org/pub/epel/6/x86_64/
    when: ansible_distribution_major_version|int == 6

  - name: install_libraries | centos5 manual rpm install | epel && asciidoc
    become: yes
    become_user: root
    when: ansible_distribution_major_version|int == 5
    shell: rpm -Uvh {{item}}
    with_items:
      - http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/centos5/epel-release-5-4.noarch.rpm

  - name: install_libraries | download s3tools repo file
    become: yes
    become_user: root
    when: ansible_distribution_major_version|int == 5
    get_url: url=http://s3.amazonaws.com/dev.hortonworks.com/ARTIFACTS/centos5/s3tools.repo dest=/etc/yum.repos.d/s3tools.repo timeout=120

  - name: install_libraries
    become: yes
    become_user: root
    yum: pkg={{item}} state=latest 
    with_items:
      - cmake3
      - gd-devel
      - libpng-devel
      - libjpeg-devel
      - cairo-devel
      - gettext-devel
      - sqlite-devel
      - intltool
      - lua-devel
      - pango-devel
  #    - xulrunner-devel
      - openssl-devel 
      - openssl-static 
      - intltool 
      - cairo-devel 
      - libxml2-devel 
      - ruby 
      - ruby-devel 
      - tcl-devel
      - gettext-devel 
      - tk-devel 
   #   - xulrunner-devel 
      - python-setuptools
      - rrdtool-python
  #    - clamav
      - python-virtualenv
      - openssh-clients
      - lsb 
      - wget 
      - openldap-devel
      - mysql-devel 
      - fuse-devel 
      - lzo-devel
      - pam-devel 
      - tetex-latex
   #   - fakeroot
      - gcc
      - cppunit 
      - cppunit-devel 
      - snappy-devel
      - xalan-j2
      - glib2
      - cpio
      - cppunit-devel
      - ant
      - libstdc++
      - ant-apache-bcel
      - zlib-devel
      - gcc-c++
      - rpm-build
      - redhat-rpm-config
      - libtool
      - fuse
      - fuse-devel
      - fuse-libs
      - xmlto
      - expect
      - cmake
      - libffi-devel
    #  - s3cmd
      - curl-devel
      - createrepo
      - subversion
      - gcc-gfortran
      - rsync
      - autoconf
      - automake
   #   - centos-release-scl
      - libevent-devel
      - bison
      - doxygen
    #  - leveldb-devel
      - libuuid-devel
      - libcurl-devel
   #   - ccache
      - pigz


