---
  - name: install_tar | Download tar
    get_url: url={{tar_url}} dest=/tmp/{{ tar_url | basename }} timeout=120

  - name: install_tar | untar tar
    unarchive: copy=no src=/tmp/{{ tar_url | basename }} dest=/tmp/

  - name: install_tar | configure, make, make install 
    become: yes
    become_user: root
    shell: cd /tmp/tar-1.28 ; export FORCE_UNSAFE_CONFIGURE=1 ; ./configure ; make && make install

  - name: install_tar | delete tarball
    become: yes
    become_user: "{{ build_user }}"
    file: path=/tmp/{{ tar_url | basename }} state=absent
