---
- name: install_python27 | check if python27 is installed
  command: "/usr/local/bin/python27 --version"
  register: check_python27
  ignore_errors: yes

# check if "check_python27" is defined and value is equal to desired python27 version
- name: install_python27 | "set fact if python27 version is {{python27_version}}"
  set_fact: python27_exists="true"
  when: check_python27.rc == 0 and check_python27.stderr.find(python27_version) != -1

- name: install_python27 | skip python27 installation
  debug: msg="skip python27 installation as it is already installed"
  when: python27_exists is defined

- name: install_tools | Mkdir python27
  become: yes
  become_user: root
  file: path={{tools_home}}/python state=directory
  when: python27_exists is not defined

- name: install_tools | Download python27
  become: yes
  become_user: root
  get_url: url=http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/Python-{{python27_version}}.tgz  dest=/tmp/Python-{{python27_version}}.tgz  mode=0644 force=yes timeout=120
  when: python27_exists is not defined

- name: install_tools | Untar python27
  become: yes
  become_user: root
  unarchive: copy=no src=/tmp/Python-{{python27_version}}.tgz  dest=/tmp/
  when: python27_exists is not defined

- name: install_tools | Configure python27
  become: yes
  become_user: root
  command: ./configure --prefix {{tools_home}}/python/{{python27_version}} chdir=/tmp/Python-{{python27_version}}
  when: python27_exists is not defined

- name: install_tools | Compile python27
  become: yes
  become_user: root
  command: make chdir=/tmp/Python-{{python27_version}}
  when: python27_exists is not defined

- name: install_tools | Install python27 non docker
  become: yes
  become_user: root
  command: make install chdir=/tmp/Python-{{python27_version}}
  when: python27_exists is not defined

- name: install_tools | Remove symlink for python27
  become: yes
  become_user: root
  file: path=/usr/local/bin/python27 state=absent
  when: python27_exists is not defined

- name: install_tools | Symlink python27
  become: yes
  become_user: root
  file:  src={{tools_home}}/python/{{python27_version}}/bin/python  dest=/usr/local/bin/python27  mode=0755 state=link force=yes
  when: python27_exists is not defined

- name: install_tools | Symlink python27
  become: yes
  become_user: root
  file: src=/usr/local/bin/python27 dest=/usr/local/bin/python mode=0755 state=link force=yes
  when: python27_exists is  defined and ( ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 5 ) or ( ansible_distribution == 'SLES' and ansible_distribution_release == '1' )

- name: install_tools | pip install
  become: yes
  become_user: root
  shell: "/usr/local/bin/python27 -m ensurepip"
  tags: install_openstack_tools
  when: project == "re" and ( ansible_distribution != 'Suse' and ansible_distribution != 'SLES' and ansible_distribution != 'Debian7')

- name: install_tools | pip upgrade | debian7
  become: yes
  become_user: root
  shell: "/usr/local/bin/pip27 install --upgrade setuptools"
  tags: install_openstack_tools
  when: project == "re" and ( ansible_distribution == "Debian" and ansible_distribution_major_version == "5")

- name: install_tools | pip install openstack packages
  become: yes
  become_user: root
  shell: "/usr/local/bin/pip2.7 install python-novaclient==2.25.0 ConcurrentLogHandler python-glanceclient jinja2 configobj"
  tags: install_openstack_tools
  when: project != "re" and ansible_virtualization_type != "docker" and ( ansible_distribution != 'Ubuntu' and ansible_distribution != 'Suse' and ansible_distribution != 'SLES')

- name: install_tools | delete python27 from /tmp
  become: yes
  become_user: root
  file: path=/tmp/Python-{{python27_version}}.tgz state=absent
  when: python27_exists is not defined
