---
  - name: install_docker | copy docker.repo
    sudo: yes
    sudo_user: root
    copy: src=files/docker.repo dest=/etc/yum.repos.d/docker.repo force=yes

  - name: install_docker | yum install docker
    sudo: yes
    sudo_user: root
    yum: name=docker-engine state=present update_cache=yes

  - name: install_docker | copy daemon.json
    sudo: yes
    sudo_user: root
    copy: src=files/daemon.json dest=/etc/docker/daemon.json force=yes

  - name: install_docker | enable docker service
    sudo: yes
    sudo_user: root
    shell: systemctl enable docker.service
 
  - name: install_docker | add jenkins user to docker group
    sudo: yes
    sudo_user: root
    shell: gpasswd -a jenkins docker    

  - name: install_docker | start docker service
    sudo: yes
    sudo_user: root
    shell: systemctl start docker 
