---
  - name: install_gradle_4102 | capture gradle version
    become: yes
    become_user: "{{ build_user }}"
    shell: "export JAVA_HOME={{tools_home}}/jdk7/latest ; {{tools_home}}/gradle/gradle-4.10.2/bin/gradle --version"
    register: check_gradle
    ignore_errors: yes
    tags: install_gradle_4102

  - name: install_gradle_4102 | "set fact if gradle version is 4.10.2"
    set_fact: gradle_exists="true"
    when: check_gradle.rc == 0 and check_gradle.stdout.find('Gradle 4.10.2') != -1
    tags: install_gradle_4102

  - name: install_gradle_4102 | skip gradle installation
    debug: msg="skip gradle installation as it is already installed"
    when: gradle_exists is defined
    tags: install_gradle_4102

  - name: install_gradle_4102 | Download gradle
    become: yes
    become_user: "{{ build_user }}"
    get_url: url=http://dev.hortonworks.com.s3.amazonaws.com/ARTIFACTS/gradle-4.10.2-bin.zip
      dest={{tools_home}}/gradle/gradle-4.10.2.zip mode=0744 force=yes timeout=120
    when: gradle_exists is not defined
    tags: install_gradle_4102

    # check if "check_gradle" is defined and value is equal to desired gradle version
  - name: install_gradle_4102 | Untar gradle
    become: yes
    become_user: "{{ build_user }}"
    unarchive: copy=no src={{tools_home}}/gradle/gradle-4.10.2.zip dest={{tools_home}}/gradle
    when: gradle_exists is not defined
    tags: install_gradle_4102

  - name: install_gradle_4102 | capture gradle version
    become: yes
    become_user: "{{ build_user }}"
    shell: "export JAVA_HOME={{tools_home}}/jdk7/latest ; {{tools_home}}/gradle/gradle-4.10.2/bin/gradle --version"
    register: cmd_result
    tags: install_gradle_4102

  - name: install_gradle_4102 | assert gradle installation
    assert:
      that:
        - "'Gradle 4.10.2' in cmd_result.stdout"
    when: gradle_exists is not defined
    tags: install_gradle_4102

  - name: install_gradle_4102 | delete gradle tarball
    become: yes
    become_user: "{{ build_user }}"
    file: path={{tools_home}}/gradle/gradle-4.10.2.zip state=absent
    when: gradle_exists is not defined
    tags: install_gradle_4102
