---
  - name: install_jdk7_80 | check if jdk7_80 is installed
    command: "{{jdk7_80_home}}/jdk{{jdk7_80_version}}/bin/java -version"
    register: check_jdk7_80
    changed_when: False
    ignore_errors: yes

  # check if "check_jdk7_80" is defined and value is equal to desired jdk7_80 version
  - name: install_jdk7_80 | "set fact if jdk7_80 version is {{jdk7_80_version}}"
    set_fact: jdk7_80_exists="true"
    when: check_jdk7_80.rc == 0 and check_jdk7_80.stderr.find(jdk7_80_version) != -1

  - name: install_jdk7_80 | skip jdk7_80 installation
    debug: msg="skip jdk7_80 installation as it is already installed"
    when: jdk7_80_exists is defined

  - name: install_jdk7_80 | "Download Jdk7" 
    become: yes
    become_user: "{{ build_user }}"
    get_url: url={{jdk7_80_url}} dest={{jdk7_80_home}}/{{ jdk7_80_url | basename }} mode=744 timeout=120
    when: jdk7_80_exists is not defined

  - name: install_jdk7_80 | "Install Jdk7"
    become: yes
    become_user: "{{ build_user }}"
    unarchive: copy=no src={{jdk7_80_home}}/{{ jdk7_80_url | basename }} dest={{jdk7_80_home}}
    when: jdk7_80_exists is not defined

  - name: install_jdk7_80 | "Symlink jdk7_80 -> latest"
    become: yes
    become_user: "{{ build_user }}"
    file: src="jdk{{jdk7_80_version}}" dest={{jdk7_80_home}}/latest state=link 
    when: jdk7_80_exists is not defined

  - name: install_jdk7_80 | Install JCE Policy files for JDK7 | Download tar
    become: yes
    become_user: "{{ build_user }}"
    get_url: url="http://s3.amazonaws.com/dev.hortonworks.com/REJENKINS/UnlimitedJCEPolicyJDK7.zip" dest={{jdk7_80_home}}/UnlimitedJCEPolicyJDK7.zip mode=744 timeout=120

  - name: install_jdk7_80 | "unzip JCE Policy files"
    become: yes
    become_user: "{{ build_user }}"
    unarchive: copy=no src={{jdk7_80_home}}/UnlimitedJCEPolicyJDK7.zip dest={{jdk7_80_home}}

  - name: install_jdk7_80 | Create lib/security for jdk7_80
    become: yes
    become_user: "{{ build_user }}"
    file: path={{ jdk7_80_home }}/jdk1.7.0_80/lib/security state=directory

  - name: install_jdk7_80 | "Install Jdk7"
    become: yes
    become_user: "{{ build_user }}"
    unarchive: copy=no src={{jdk7_80_home}}/UnlimitedJCEPolicyJDK7.zip dest={{jdk7_80_home}}/

  - name: install_jdk7_80 | "copy JCE Policy files for JDK7"
    become: yes
    become_user: "{{ build_user }}"
    shell: cp -r {{jdk7_80_home}}/UnlimitedJCEPolicy/*.jar {{jdk7_80_home}}/jdk1.7.0_80/lib/security/

  - name: install_jdk7_80 | delete jdk tarball
    become: yes
    become_user: "{{ build_user }}"
    file: path={{jdk7_80_home}}/{{ jdk7_80_url | basename }} state=absent

  - name: install_jdk7_80 | delete JCE Policy files tarball
    become: yes
    become_user: "{{ build_user }}"
    file: path={{jdk7_80_home}}/UnlimitedJCEPolicyJDK7.zip state=absent
