---
  - name: install_libraries | uninstall 
    sudo: yes
    sudo_user: root
    yum: pkg={{item}} state=absent
    with_items:
      - postgresql-libs

  - name: install_libraries | 
    sudo: yes
    sudo_user: root
    tags: install_libs
    yum: pkg={{item}} state=latest 
    with_items:
      - gd-devel
      - libpng-devel
      - libjpeg-devel
      - cairo-devel
      - gettext-devel
      - intltool
      - lua-devel
      - pango-devel
      - xulrunner-devel
      - openssl-devel 
      - intltool 
      - cairo-devel 
      - pango-devel 
      - libxml2-devel 
      - ruby 
      - ruby-devel 
      - tcl-devel
      - gettext-devel 
      - lua-devel 
      - tk-devel 
      - xulrunner-devel 
      - python-setuptools
      - rrdtool-python
      - clamav

  - name: install-python-argparse | install python spare libs
    sudo: yes
    easy_install: name=pip
    easy_install: name=argparse
    easy_install: name=requests
    tags:   install_argparse
  
  - name: Install_Libraries | Install Ruby Libraries and build Tools
    sudo: yes
    sudo_user: root
    yum: name={{item}}  state=latest
    tags: install_rubygems
    with_items:
        - rubygems
  
  - name: Install_Libraries | Install Ruby Libraries and Debian build Tools
    sudo: yes
    sudo_user: root
    gem:  name=gem2deb
    gem:  name=json
    tags: install_rubygems
