---
- name: check if build_user is set
  fail: msg='Bailing out. this play requires username, Please pass in the form  -e \"build_user=xyz\"'
  when: build_user is not defined

- include: common/setup_user.yml

- include_vars: "{{ secret_profile_file }}"

- include: setup_user_sshkeys.yml
  when: ssh_url is defined

- include: readonly_sshkeys.yml
  when: readonly_ssh is defined

- include: prepare_env.yml

- include: install_jdk10.yml

- include: install_jdk8.yml

- include: install_jdk8_171.yml

#- include: install_gradle.yml

- include: install_gradle_50.yml

- include: install_maven.yml

- include: install_ant.yml

- include: install_sonar_ant_task.yml

- include: install_tools.yml

- include: setup_user_configs.yml
  when: project != 'dev' and build_user != "nobody"

- include: update_configs.yml
  when: build_user != "nobody"

- include: centos_install_libraries.yml

- include: install_r.yml

- include: centos7_install_libraries.yml

- include: install_gcc.yml

- include: install_cmake.yml

- include: install_git.yml

- include: install_protobuf.yml
    protobuf_version="2.5.0"
    protobuf_home="/opt"

- include: install_autoconf.yml

- include: install_node_js.yml

- include: install_python36.yml

- include: install_asciidoc.yml

- include: install_awscli.yml

- include: install_clamav.yml

- include: install_helm.yml

- include: install_boost.yml

- include: install_bison.yml

- include: install_kube_docker_util.yml

