---
  - name: "make sure script is not there.."
    file: path=/tmp/monitor.sh state=absent

  - name: "copy over a monitoring script."
    copy: src=monitor.sh  dest=/tmp/monitor.sh

  - name: "Run that monitoring script."
    shell: MAX="{{upperbound}}" sh /tmp/monitor.sh
    register: mergatroid

  - name: "Tell what we learned."
    debug: msg="{{mergatroid}}"

  - name: "remove script ."
    file: path=/tmp/monitor.sh state=absent

