FROM registry.eng.hortonworks.com/hortonworks/base-sles12sp1:0.1.0.0-102 

RUN zypper install -y  unzip
RUN pip install ansible==2.9.0
RUN ansible --version
COPY . /root/ansible/


ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV LANG C.UTF-8
ENV ANSIBLE_CONFIG=/root/ansible/ansible/config/ansible.cfg
RUN ansible-playbook /root/ansible/ansible/playbooks/setup-images/setup_sles12.yml  -e "username=jenkins project_name=re" -i /root/ansible/ansible/config/docker_hosts --vault-password-file=/root/ansible/re_vault_pass.txt --connection=local

