FROM registry.eng.hortonworks.com/hortonworks/base-sles11sp3:0.1.0.0-75

RUN zypper ar http://sles-repos-re.eng.hortonworks.com/sles11sp3 hosted_sp3
RUN sed -i  "s/172.22.77.245/sles-repos-re.eng.hortonworks.com/g" /etc/zypp/repos.d/hw-sles-11.3.repo 
RUN zypper install -y --force-resolution gcc43-c++ unzip
RUN zypper remove -y ansible python-crypto

RUN wget https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz --no-check-certificate
RUN tar xvfz Python-2.7.12.tgz
RUN cd Python-2.7.12 && ./configure --prefix=/opt/python2.7 --enable-shared && make && make altinstall && echo "/opt/python2.7/lib" >> /etc/ld.so.conf.d/opt-python2.7.conf
ldconfig
COPY . /root/ansible/

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV LANG C.UTF-8
ENV ANSIBLE_CONFIG=/root/ansible/ansible/config/ansible.cfg
RUN ansible-playbook /root/ansible/ansible/playbooks/setup-images/setup_suse11sp3.yml  -e "username=jenkins project_name=re" -i /root/ansible/ansible/config/docker_hosts --vault-password-file=/root/ansible/re_vault_pass.txt --connection=local

