FROM registry.eng.hortonworks.com/hortonworks/base-sles11sp3:0.1.0.0-75

RUN zypper ar http://172.22.77.245/sles11sp3 hosted_sp3
RUN zypper install -y --force-resolution gcc43-c++ unzip

RUN zypper remove -y ansible python-crypto

RUN pip install ansible==2.9.0
COPY . /root/ansible/

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV LANG C.UTF-8
ENV ANSIBLE_CONFIG=/root/ansible/ansible/config/ansible.cfg
RUN ansible-playbook /root/ansible/ansible/playbooks/setup-images/setup_suse11sp3.yml  -e "username=jenkins project_name=re" -i /root/ansible/ansible/config/docker_hosts --vault-password-file=/root/ansible/re_vault_pass.txt --connection=local

